[workspace]
members = ["crates/valet-policy-engine"]
resolver = "2"

[workspace.package]
edition = "2021"
license = "MIT"
rust-version = "1.98.1"

[workspace.dependencies]
regorus = { git = "https://github.com/tkhq/regorus", rev = "309ba35067d2118aafd696198a33037f5af9e1bd", default-features = false, features = ["arc", "base64", "base64url", "glob", "graph", "hex", "jsonpatch", "no_std", "regex", "semver", "urlquery", "yaml"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_jcs = "0.1"
anyhow = "1.0"
thiserror = "2.0"
