[workspace]
members = ["crates/valet-policy-engine", "crates/valet-policy-engine-wasm"]
resolver = "2"

[workspace.package]
edition = "2021"
license = "MIT"
rust-version = "1.98.1"

[workspace.dependencies]
regorus = { git = "https://github.com/tkhq/regorus", rev = "f938ef286fdf9b229d3933b064dfd87323f397e8", default-features = false, features = ["arc", "base64", "base64url", "glob", "graph", "hex", "jsonpatch", "no_std", "regex", "semver", "urlquery", "yaml"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_jcs = "0.1"
anyhow = "1.0"
thiserror = "2.0"
sha2 = "0.10"
base64 = "0.22"
wasm-bindgen = "=0.2.128"
