/* Generated from the mounted Hono inventory, then reviewed. Do not infer descriptors at runtime. */
import type { RouterRoute } from "hono/types";
export type PolicyRisk = "low" | "medium" | "high" | "critical";
export type ResourceKind = "repository" | "secret" | "policy" | "workflow" | "artifact" | "session" | "assistant" | "team";
export type ResourceOperation = "create" | "list" | "metadata" | "read" | "update" | "delete" | "execute" | "approve" | "cancel" | "share" | "publish" | "import" | "export" | "attach" | "use" | "link" | "unlink" | "copy";
export interface ResourceAccessDescriptorV1 { readonly schemaVersion: 1; readonly resourceKind: ResourceKind; readonly operation: ResourceOperation; readonly service: string; readonly actionId: string; readonly riskLevel: PolicyRisk; readonly safeMetadata: readonly ["resourceId", "ownerType", "ownerId", "version"]; }
export const RESOURCE_ACCESS_DESCRIPTOR_SEEDS_V1: Readonly<Record<string, readonly [PolicyRisk]>> = Object.freeze({
  "repository.list": ["low"], "repository.metadata": ["low"], "repository.link": ["low"], "repository.unlink": ["low"], "repository.import": ["medium"],
  "secret.list": ["high"], "secret.metadata": ["high"], "secret.create": ["high"], "secret.update": ["high"], "secret.delete": ["high"], "secret.attach": ["high"],
  "policy.list": ["low"], "policy.read": ["low"], "policy.create": ["medium"], "policy.update": ["medium"], "policy.delete": ["high"], "policy.approve": ["high"], "policy.publish": ["high"],
  "workflow.list": ["low"], "workflow.read": ["low"], "workflow.create": ["medium"], "workflow.update": ["medium"], "workflow.delete": ["high"], "workflow.execute": ["medium"],
  "artifact.delete": ["high"], "artifact.share": ["medium"], "artifact.publish": ["high"], "artifact.copy": ["low"],
  "session.update": ["medium"], "session.delete": ["high"],
  "assistant.update": ["medium"], "assistant.delete": ["high"],
  "team.update": ["medium"], "team.delete": ["high"],
});
export const RESOURCE_ACCESS_REGISTRY: readonly ResourceAccessDescriptorV1[] = Object.freeze(Object.entries(RESOURCE_ACCESS_DESCRIPTOR_SEEDS_V1).map(([key, [riskLevel]]) => { const split = key.indexOf("."); const resourceKind = key.slice(0, split) as ResourceKind, operation = key.slice(split + 1) as ResourceOperation; return Object.freeze({ schemaVersion: 1 as const, resourceKind, operation, service: `resource_${resourceKind}`, actionId: `resource_${resourceKind}.${operation}`, riskLevel, safeMetadata: ["resourceId", "ownerType", "ownerId", "version"] as const }); }));
export interface ApiRouteDescriptorV1 { readonly schemaVersion: 1; readonly method: string; readonly template: string; readonly service: string; readonly actionId: string; readonly operation: ResourceOperation; readonly riskLevel: PolicyRisk; readonly approvalSupported: boolean; readonly safeProjection: { readonly kind: "no_body" } | { readonly kind: "json_fields"; readonly fields: readonly string[] } | { readonly kind: "unsupported" }; readonly obligations: readonly []; readonly audit: { readonly group: string }; readonly resourceKind?: ResourceKind; }
export interface BoundaryExclusionV1 { readonly schemaVersion: 1; readonly key: string; readonly classification: "public" | "pr12_owned"; readonly rationale: string; }
type Seed = readonly [service: string, actionId: string, operation: ResourceOperation, risk: PolicyRisk, resourceKind?: ResourceKind];
const SAFE_ROUTE_PROJECTIONS_V1: Readonly<Record<string, ApiRouteDescriptorV1["safeProjection"]>> = Object.freeze({
  "POST /api/sessions": { kind: "json_fields", fields: ["workspace", "title", "teamId", "kind", "model", "profile", "docker", "preset", "paths", "rescanOf"] },
});
export function mergeApiRouteDescriptorMapsV1(...maps: readonly Readonly<Record<string, Seed>>[]): Readonly<Record<string, Seed>> {
  const merged: Record<string, Seed> = {};
  for (const map of maps) for (const [key, descriptor] of Object.entries(map)) {
    const prior = merged[key];
    if (prior !== undefined && JSON.stringify(prior) !== JSON.stringify(descriptor)) throw new Error(`Conflicting API route descriptor: ${key}.`);
    merged[key] = descriptor;
  }
  return Object.freeze(merged);
}

export const API_ROUTE_DESCRIPTOR_SEEDS_V1: Readonly<Record<string, Seed>> = Object.freeze({
  "POST /api/authorization/decisions/:decisionId/resolve": ["api_authorization", "api_authorization.post_authorization_decisions_item_resolve", "approve", "high", "policy"],
  "DELETE /api/admin/*": ["api_admin", "api_admin.delete_admin_item", "delete", "high"],
  "DELETE /api/artifacts/:id": ["api_artifacts", "api_artifacts.delete_artifacts_item", "delete", "high", "artifact"],
  "DELETE /api/assistants/:id": ["api_assistants", "api_assistants.delete_assistants_item", "delete", "high", "assistant"],
  "DELETE /api/event-subscriptions/:id": ["api_event_subscriptions", "api_event_subscriptions.delete_event_subscriptions_item", "delete", "high"],
  "DELETE /api/me/github": ["api_me", "api_me.delete_me_github", "delete", "high"],
  "DELETE /api/me/grants": ["api_me", "api_me.delete_me_grants", "delete", "high", "policy"],
  "DELETE /api/me/identity-links/:provider": ["api_me", "api_me.delete_me_identity_links_item", "delete", "high"],
  "DELETE /api/me/policy-overrides": ["api_me", "api_me.delete_me_policy_overrides", "delete", "high", "policy"],
  "DELETE /api/org/github-app": ["api_org", "api_org.delete_org_github_app", "delete", "high"],
  "DELETE /api/org/invites/:id": ["api_org", "api_org.delete_org_invites_item", "delete", "high"],
  "DELETE /api/org/linear": ["api_org", "api_org.delete_org_linear", "delete", "high"],
  "DELETE /api/org/policies/:id": ["api_org", "api_org.delete_org_policies_item", "delete", "high", "policy"],
  "DELETE /api/org/sources/:id": ["api_org", "api_org.delete_org_sources_item", "delete", "high"],
  "DELETE /api/sessions/:id": ["api_sessions", "api_sessions.delete_sessions_item", "delete", "high", "session"],
  "DELETE /api/skills/sources/:id": ["api_skills", "api_skills.delete_skills_sources_item", "delete", "high"],
  "DELETE /api/skills/stored/:id": ["api_skills", "api_skills.delete_skills_stored_item", "delete", "high"],
  "DELETE /api/teams/:id": ["api_teams", "api_teams.delete_teams_item", "delete", "high", "team"],
  "DELETE /api/teams/:id/api-keys/:keyId": ["api_teams", "api_teams.delete_teams_item_api_keys_item", "delete", "high", "team"],
  "DELETE /api/teams/:id/deletion-requests/*": ["api_teams", "api_teams.delete_teams_item_deletion_requests_item", "delete", "high", "team"],
  "DELETE /api/teams/:id/grants/:grantId": ["api_teams", "api_teams.delete_teams_item_grants_item", "delete", "high", "policy"],
  "DELETE /api/teams/:id/members/:userId": ["api_teams", "api_teams.delete_teams_item_members_item", "delete", "high", "team"],
  "DELETE /api/teams/:id/policies": ["api_teams", "api_teams.delete_teams_item_policies", "delete", "high", "policy"],
  "DELETE /api/teams/:id/policies/:policyId": ["api_teams", "api_teams.delete_teams_item_policies_item", "delete", "high", "policy"],
  "DELETE /api/teams/:id/policy-overrides": ["api_teams", "api_teams.delete_teams_item_policy_overrides", "delete", "high", "policy"],
  "DELETE /api/workflows/:id": ["api_workflows", "api_workflows.delete_workflows_item", "delete", "high", "workflow"],
  "DELETE /api/workflows/:id/schedules/:scheduleId": ["api_workflows", "api_workflows.delete_workflows_item_schedules_item", "delete", "high", "workflow"],
  "DELETE /api/workflows/:id/webhook": ["api_workflows", "api_workflows.delete_workflows_item_webhook", "delete", "high", "workflow"],
  "DELETE /api/workflows/event-triggers/:id": ["api_workflows", "api_workflows.delete_workflows_event_triggers_item", "delete", "high", "workflow"],
  "DELETE /api/workflows/schedules/:id": ["api_workflows", "api_workflows.delete_workflows_schedules_item", "delete", "high", "workflow"],
  "GET /api/admin/*": ["api_admin", "api_admin.get_admin_item", "list", "low"],
  "GET /api/admin/submissions": ["api_admin", "api_admin.get_admin_submissions", "list", "low"],
  "GET /api/artifacts": ["api_artifacts", "api_artifacts.get_artifacts", "list", "low", "artifact"],
  "GET /api/artifacts/:id/versions": ["api_artifacts", "api_artifacts.get_artifacts_item_versions", "read", "low", "artifact"],
  "GET /api/assistants": ["api_assistants", "api_assistants.get_assistants", "list", "low", "assistant"],
  "GET /api/changelog": ["api_changelog", "api_changelog.get_changelog", "list", "low"],
  "GET /api/evals/flagged": ["api_evals", "api_evals.get_evals_flagged", "list", "low"],
  "GET /api/event-subscriptions": ["api_event_subscriptions", "api_event_subscriptions.get_event_subscriptions", "list", "low"],
  "GET /api/events": ["api_events", "api_events.get_events", "list", "low"],
  "GET /api/events/:id": ["api_events", "api_events.get_events_item", "read", "low"],
  "GET /api/events/catalog": ["api_events", "api_events.get_events_catalog", "list", "low"],
  "GET /api/events/drops": ["api_events", "api_events.get_events_drops", "list", "low"],
  "GET /api/events/filter-options": ["api_events", "api_events.get_events_filter_options", "list", "low"],
  "GET /api/me": ["api_me", "api_me.get_me", "list", "low"],
  "GET /api/me/github/callback": ["api_me", "api_me.get_me_github_callback", "list", "low"],
  "GET /api/me/github/org-status": ["api_me", "api_me.get_me_github_org_status", "list", "low"],
  "GET /api/me/grants": ["api_me", "api_me.get_me_grants", "list", "low", "policy"],
  "GET /api/me/identity-links": ["api_me", "api_me.get_me_identity_links", "list", "low"],
  "GET /api/me/identity-links/:provider/members": ["api_me", "api_me.get_me_identity_links_item_members", "read", "low"],
  "GET /api/me/policy-overrides": ["api_me", "api_me.get_me_policy_overrides", "list", "low", "policy"],
  "GET /api/models": ["api_models", "api_models.get_models", "list", "low"],
  "GET /api/models/registry-status": ["api_models", "api_models.get_models_registry_status", "list", "low"],
  "GET /api/notifications": ["api_notifications", "api_notifications.get_notifications", "list", "low"],
  "GET /api/notifications/preferences": ["api_notifications", "api_notifications.get_notifications_preferences", "list", "low"],
  "GET /api/orchestrator": ["api_orchestrator", "api_orchestrator.get_orchestrator", "list", "low"],
  "GET /api/orchestrator/children": ["api_orchestrator", "api_orchestrator.get_orchestrator_children", "list", "low"],
  "GET /api/orchestrator/info": ["api_orchestrator", "api_orchestrator.get_orchestrator_info", "list", "low"],
  "GET /api/org": ["api_org", "api_org.get_org", "list", "low"],
  "GET /api/org/action-log": ["api_org", "api_org.get_org_action_log", "list", "low", "policy"],
  "GET /api/org/approved-models": ["api_org", "api_org.get_org_approved_models", "approve", "high"],
  "GET /api/org/directory": ["api_org", "api_org.get_org_directory", "list", "low"],
  "GET /api/org/github-app": ["api_org", "api_org.get_org_github_app", "list", "low"],
  "GET /api/org/github-app/setup": ["api_org", "api_org.get_org_github_app_setup", "list", "low"],
  "GET /api/org/invites": ["api_org", "api_org.get_org_invites", "list", "low"],
  "GET /api/org/linear": ["api_org", "api_org.get_org_linear", "list", "low"],
  "GET /api/org/linear/callback": ["api_org", "api_org.get_org_linear_callback", "list", "low"],
  "GET /api/org/members": ["api_org", "api_org.get_org_members", "list", "low"],
  "GET /api/org/model-tiers": ["api_org", "api_org.get_org_model_tiers", "list", "low"],
  "GET /api/org/plugins": ["api_org", "api_org.get_org_plugins", "list", "low"],
  "GET /api/org/policies": ["api_org", "api_org.get_org_policies", "list", "low", "policy"],
  "GET /api/org/policy-drafts/contexts": ["api_org", "api_org.get_org_policy_drafts_contexts", "read", "low", "policy"],
  "GET /api/org/policy-drafts": ["api_org", "api_org.get_org_policy_drafts", "list", "low", "policy"],
  "GET /api/org/policy-drafts/:documentId": ["api_org", "api_org.get_org_policy_drafts_item", "read", "low", "policy"],
  "GET /api/org/policy-drafts/:documentId/diff": ["api_org", "api_org.get_org_policy_drafts_item_diff", "read", "low", "policy"],
  "GET /api/org/reasoning": ["api_org", "api_org.get_org_reasoning", "list", "low"],
  "GET /api/org/slack": ["api_org", "api_org.get_org_slack", "list", "low"],
  "GET /api/org/sources": ["api_org", "api_org.get_org_sources", "list", "low"],
  "GET /api/org/sources/:id/bakes": ["api_org", "api_org.get_org_sources_item_bakes", "read", "low"],
  "GET /api/org/sources/health": ["api_org", "api_org.get_org_sources_health", "list", "low"],
  "GET /api/org/sources/queue": ["api_org", "api_org.get_org_sources_queue", "list", "low"],
  "GET /api/plugins": ["api_plugins", "api_plugins.get_plugins", "list", "low"],
  "GET /api/proxy/requests": ["api_proxy", "api_proxy.get_proxy_requests", "list", "low"],
  "GET /api/proxy/requests/:id": ["api_proxy", "api_proxy.get_proxy_requests_item", "read", "low"],
  "GET /api/proxy/settings": ["api_proxy", "api_proxy.get_proxy_settings", "list", "low"],
  "GET /api/proxy/usage/summary": ["api_proxy", "api_proxy.get_proxy_usage_summary", "list", "low"],
  "GET /api/repos": ["api_repos", "api_repos.get_repos", "list", "low", "repository"],
  "GET /api/sessions": ["api_sessions", "api_sessions.get_sessions", "list", "low", "session"],
  "GET /api/sessions/:id": ["api_sessions", "api_sessions.get_sessions_item", "read", "low", "session"],
  "GET /api/sessions/:id/commands": ["api_sessions", "api_sessions.get_sessions_item_commands", "read", "low", "session"],
  "GET /api/sessions/:id/decisions": ["api_sessions", "api_sessions.get_sessions_item_decisions", "read", "low", "session"],
  "GET /api/sessions/:id/messages": ["api_sessions", "api_sessions.get_sessions_item_messages", "execute", "medium", "session"],
  "GET /api/sessions/:id/ratings": ["api_sessions", "api_sessions.get_sessions_item_ratings", "read", "low", "session"],
  "GET /api/sessions/:id/security": ["api_sessions", "api_sessions.get_sessions_item_security", "read", "low", "session"],
  "GET /api/sessions/:id/security/coverage": ["api_sessions", "api_sessions.get_sessions_item_security_coverage", "read", "low", "session"],
  "GET /api/sessions/:id/security/export": ["api_sessions", "api_sessions.get_sessions_item_security_export", "export", "medium", "session"],
  "GET /api/sessions/:id/security/files": ["api_sessions", "api_sessions.get_sessions_item_security_files", "read", "low", "session"],
  "GET /api/sessions/:id/security/files/list": ["api_sessions", "api_sessions.get_sessions_item_security_files_list", "read", "low", "session"],
  "GET /api/sessions/:id/security/findings": ["api_sessions", "api_sessions.get_sessions_item_security_findings", "read", "low", "session"],
  "GET /api/sessions/:id/security/needs": ["api_sessions", "api_sessions.get_sessions_item_security_needs", "read", "low", "session"],
  "GET /api/sessions/:id/security/report": ["api_sessions", "api_sessions.get_sessions_item_security_report", "read", "low", "repository"],
  "GET /api/sessions/:id/security/report/export": ["api_sessions", "api_sessions.get_sessions_item_security_report_export", "export", "medium", "repository"],
  "GET /api/sessions/:id/security/start-preview": ["api_sessions", "api_sessions.get_sessions_item_security_start_preview", "execute", "medium", "session"],
  "GET /api/sessions/:id/security/status": ["api_sessions", "api_sessions.get_sessions_item_security_status", "read", "low", "session"],
  "GET /api/sessions/:id/threads": ["api_sessions", "api_sessions.get_sessions_item_threads", "read", "low", "session"],
  "GET /api/sessions/:id/ws": ["api_sessions", "api_sessions.get_sessions_item_ws", "read", "low", "session"],
  "GET /api/skills": ["api_skills", "api_skills.get_skills", "list", "low"],
  "GET /api/skills/:name": ["api_skills", "api_skills.get_skills_item", "read", "low"],
  "GET /api/skills/sources": ["api_skills", "api_skills.get_skills_sources", "list", "low"],
  "GET /api/skills/stored/:id": ["api_skills", "api_skills.get_skills_stored_item", "read", "low"],
  "GET /api/sources/for-repo": ["api_sources", "api_sources.get_sources_for_repo", "list", "low"],
  "GET /api/teams": ["api_teams", "api_teams.get_teams", "list", "low", "team"],
  "GET /api/teams/:id/api-keys": ["api_teams", "api_teams.get_teams_item_api_keys", "read", "low", "team"],
  "GET /api/teams/:id/children": ["api_teams", "api_teams.get_teams_item_children", "read", "low", "team"],
  "GET /api/teams/:id/deletion-requests": ["api_teams", "api_teams.get_teams_item_deletion_requests", "read", "low", "team"],
  "GET /api/teams/:id/deletion-requests/*": ["api_teams", "api_teams.get_teams_item_deletion_requests_item", "read", "low", "team"],
  "GET /api/teams/:id/deletion-requests/targets": ["api_teams", "api_teams.get_teams_item_deletion_requests_targets", "read", "low", "team"],
  "GET /api/teams/:id/grants": ["api_teams", "api_teams.get_teams_item_grants", "read", "low", "policy"],
  "GET /api/teams/:id/members": ["api_teams", "api_teams.get_teams_item_members", "read", "low", "team"],
  "GET /api/teams/:id/policies": ["api_teams", "api_teams.get_teams_item_policies", "read", "low", "policy"],
  "GET /api/teams/:teamId/policy-drafts/contexts": ["api_teams", "api_teams.get_teams_item_policy_drafts_contexts", "read", "low", "policy"],
  "GET /api/teams/:teamId/policy-drafts": ["api_teams", "api_teams.get_teams_item_policy_drafts", "read", "low", "policy"],
  "GET /api/teams/:teamId/policy-drafts/:documentId": ["api_teams", "api_teams.get_teams_item_policy_drafts_item", "read", "low", "policy"],
  "GET /api/teams/:teamId/policy-drafts/:documentId/diff": ["api_teams", "api_teams.get_teams_item_policy_drafts_item_diff", "read", "low", "policy"],
  "GET /api/teams/suggestions": ["api_teams", "api_teams.get_teams_suggestions", "list", "low", "team"],
  "GET /api/templates": ["api_templates", "api_templates.get_templates", "list", "low"],
  "GET /api/usage/breakdown": ["api_usage", "api_usage.get_usage_breakdown", "list", "low"],
  "GET /api/usage/daily-agents": ["api_usage", "api_usage.get_usage_daily_agents", "list", "low"],
  "GET /api/usage/export.csv": ["api_usage", "api_usage.get_usage_export_csv", "export", "medium"],
  "GET /api/usage/items": ["api_usage", "api_usage.get_usage_items", "list", "low"],
  "GET /api/usage/sessions": ["api_usage", "api_usage.get_usage_sessions", "list", "low"],
  "GET /api/usage/summary": ["api_usage", "api_usage.get_usage_summary", "list", "low"],
  "GET /api/workflows": ["api_workflows", "api_workflows.get_workflows", "list", "low", "workflow"],
  "GET /api/workflows/:id": ["api_workflows", "api_workflows.get_workflows_item", "read", "low", "workflow"],
  "GET /api/workflows/:id/file": ["api_workflows", "api_workflows.get_workflows_item_file", "read", "low", "workflow"],
  "GET /api/workflows/:id/permissions": ["api_workflows", "api_workflows.get_workflows_item_permissions", "read", "low", "workflow"],
  "GET /api/workflows/:id/runs": ["api_workflows", "api_workflows.get_workflows_item_runs", "execute", "medium", "workflow"],
  "GET /api/workflows/:id/schedules": ["api_workflows", "api_workflows.get_workflows_item_schedules", "read", "low", "workflow"],
  "GET /api/workflows/:id/versions": ["api_workflows", "api_workflows.get_workflows_item_versions", "read", "low", "workflow"],
  "GET /api/workflows/:id/versions/:version": ["api_workflows", "api_workflows.get_workflows_item_versions_item", "read", "low", "workflow"],
  "GET /api/workflows/:id/webhook": ["api_workflows", "api_workflows.get_workflows_item_webhook", "read", "low", "workflow"],
  "GET /api/workflows/import/repo-file": ["api_workflows", "api_workflows.get_workflows_import_repo_file", "import", "medium", "repository"],
  "GET /api/workflows/runs": ["api_workflows", "api_workflows.get_workflows_runs", "execute", "medium", "workflow"],
  "GET /api/workflows/runs/:runId": ["api_workflows", "api_workflows.get_workflows_runs_item", "execute", "medium", "workflow"],
  "GET /api/workflows/trigger-catalog": ["api_workflows", "api_workflows.get_workflows_trigger_catalog", "list", "low", "workflow"],
  "GET /api/workflows/triggers": ["api_workflows", "api_workflows.get_workflows_triggers", "list", "low", "workflow"],
  "HEAD /api/admin/*": ["api_admin", "api_admin.head_admin_item", "list", "low"],
  "HEAD /api/teams/:id/deletion-requests/*": ["api_teams", "api_teams.head_teams_item_deletion_requests_item", "read", "low", "team"],
  "OPTIONS /api/admin/*": ["api_admin", "api_admin.options_admin_item", "list", "low"],
  "OPTIONS /api/teams/:id/deletion-requests/*": ["api_teams", "api_teams.options_teams_item_deletion_requests_item", "read", "low", "team"],
  "PATCH /api/admin/*": ["api_admin", "api_admin.patch_admin_item", "update", "medium"],
  "PATCH /api/artifacts/:id": ["api_artifacts", "api_artifacts.patch_artifacts_item", "update", "medium", "artifact"],
  "PATCH /api/assistants/:id": ["api_assistants", "api_assistants.patch_assistants_item", "update", "medium", "assistant"],
  "PATCH /api/event-subscriptions/:id": ["api_event_subscriptions", "api_event_subscriptions.patch_event_subscriptions_item", "update", "medium"],
  "PATCH /api/me": ["api_me", "api_me.patch_me", "update", "medium"],
  "PATCH /api/me/identity-links/:provider": ["api_me", "api_me.patch_me_identity_links_item", "update", "medium"],
  "PATCH /api/orchestrator/info": ["api_orchestrator", "api_orchestrator.patch_orchestrator_info", "update", "medium"],
  "PATCH /api/org": ["api_org", "api_org.patch_org", "update", "medium"],
  "PATCH /api/org/members/:userId": ["api_org", "api_org.patch_org_members_item", "update", "medium"],
  "PATCH /api/org/model-tiers": ["api_org", "api_org.patch_org_model_tiers", "update", "medium"],
  "PATCH /api/org/plugins/:name": ["api_org", "api_org.patch_org_plugins_item", "update", "medium"],
  "PATCH /api/org/policies/:id": ["api_org", "api_org.patch_org_policies_item", "update", "medium", "policy"],
  "PATCH /api/org/policy-drafts/:documentId": ["api_org", "api_org.patch_org_policy_drafts_item", "update", "medium", "policy"],
  "PATCH /api/org/reasoning": ["api_org", "api_org.patch_org_reasoning", "update", "medium"],
  "PATCH /api/org/settings": ["api_org", "api_org.patch_org_settings", "update", "medium"],
  "PATCH /api/org/sources/:id": ["api_org", "api_org.patch_org_sources_item", "update", "medium"],
  "PATCH /api/org/sources/queue": ["api_org", "api_org.patch_org_sources_queue", "update", "medium"],
  "PATCH /api/sessions/:id": ["api_sessions", "api_sessions.patch_sessions_item", "update", "medium", "session"],
  "PATCH /api/sessions/:id/threads/:threadId": ["api_sessions", "api_sessions.patch_sessions_item_threads_item", "update", "medium", "session"],
  "PATCH /api/skills/stored/:id": ["api_skills", "api_skills.patch_skills_stored_item", "update", "medium"],
  "PATCH /api/teams/:id": ["api_teams", "api_teams.patch_teams_item", "update", "medium", "team"],
  "PATCH /api/teams/:id/deletion-requests/*": ["api_teams", "api_teams.patch_teams_item_deletion_requests_item", "update", "medium", "team"],
  "PATCH /api/teams/:id/members/:userId": ["api_teams", "api_teams.patch_teams_item_members_item", "update", "medium", "team"],
  "PATCH /api/teams/:id/policies": ["api_teams", "api_teams.patch_teams_item_policies", "update", "medium", "policy"],
  "PATCH /api/teams/:id/policies/:policyId": ["api_teams", "api_teams.patch_teams_item_policies_item", "update", "medium", "policy"],
  "PATCH /api/teams/:teamId/policy-drafts/:documentId": ["api_teams", "api_teams.patch_teams_item_policy_drafts_item", "update", "medium", "policy"],
  "PATCH /api/workflows/event-triggers/:id": ["api_workflows", "api_workflows.patch_workflows_event_triggers_item", "update", "medium", "workflow"],
  "PATCH /api/workflows/schedules/:id": ["api_workflows", "api_workflows.patch_workflows_schedules_item", "update", "medium", "workflow"],
  "POST /api/admin/*": ["api_admin", "api_admin.post_admin_item", "create", "medium"],
  "POST /api/admin/submissions/:sessionId/:itemId/force-settle": ["api_admin", "api_admin.post_admin_submissions_item_item_force_settle", "create", "medium"],
  "POST /api/artifacts/copy-to-team": ["api_artifacts", "api_artifacts.post_artifacts_copy_to_team", "copy", "low", "artifact"],
  "POST /api/artifacts/share": ["api_artifacts", "api_artifacts.post_artifacts_share", "share", "medium", "artifact"],
  "POST /api/assistants": ["api_assistants", "api_assistants.post_assistants", "create", "medium", "assistant"],
  "POST /api/assistants/:id/avatar": ["api_assistants", "api_assistants.post_assistants_item_avatar", "create", "medium", "assistant"],
  "POST /api/assistants/:id/session": ["api_assistants", "api_assistants.post_assistants_item_session", "create", "medium", "assistant"],
  "POST /api/event-subscriptions": ["api_event_subscriptions", "api_event_subscriptions.post_event_subscriptions", "create", "medium"],
  "POST /api/events/:id/redeliver": ["api_events", "api_events.post_events_item_redeliver", "create", "medium"],
  "POST /api/me/avatar": ["api_me", "api_me.post_me_avatar", "create", "medium"],
  "POST /api/me/github/connect": ["api_me", "api_me.post_me_github_connect", "create", "medium"],
  "POST /api/me/identity-links/:provider/deliver": ["api_me", "api_me.post_me_identity_links_item_deliver", "create", "medium"],
  "POST /api/me/identity-links/:provider/start": ["api_me", "api_me.post_me_identity_links_item_start", "execute", "medium"],
  "POST /api/notifications/:id/read": ["api_notifications", "api_notifications.post_notifications_item_read", "create", "medium"],
  "POST /api/notifications/read-all": ["api_notifications", "api_notifications.post_notifications_read_all", "create", "medium"],
  "POST /api/orchestrator": ["api_orchestrator", "api_orchestrator.post_orchestrator", "create", "medium"],
  "POST /api/orchestrator/children/:childSessionId/dismiss": ["api_orchestrator", "api_orchestrator.post_orchestrator_children_item_dismiss", "create", "medium"],
  "POST /api/org/github-app/credential": ["api_org", "api_org.post_org_github_app_credential", "create", "medium"],
  "POST /api/org/github-app/manifest": ["api_org", "api_org.post_org_github_app_manifest", "create", "medium"],
  "POST /api/org/github-app/refresh": ["api_org", "api_org.post_org_github_app_refresh", "create", "medium"],
  "POST /api/org/invites": ["api_org", "api_org.post_org_invites", "create", "medium"],
  "POST /api/org/linear/connect": ["api_org", "api_org.post_org_linear_connect", "create", "medium"],
  "POST /api/org/policies": ["api_org", "api_org.post_org_policies", "create", "medium", "policy"],
  "POST /api/org/policies/preview": ["api_org", "api_org.post_org_policies_preview", "create", "medium", "policy"],
  "POST /api/org/policy-drafts": ["api_org", "api_org.post_org_policy_drafts", "create", "medium", "policy"],
  "POST /api/org/policy-drafts/:documentId/prepare-publication": ["api_org", "api_org.post_org_policy_drafts_item_prepare_publication", "create", "medium", "policy"],
  "POST /api/org/policy-drafts/:documentId/restore/:revision": ["api_org", "api_org.post_org_policy_drafts_item_restore_item", "create", "medium", "policy"],
  "POST /api/org/policy-drafts/:documentId/reviews": ["api_org", "api_org.post_org_policy_drafts_item_reviews", "approve", "high", "policy"],
  "POST /api/org/policy-drafts/:documentId/submit-review": ["api_org", "api_org.post_org_policy_drafts_item_submit_review", "create", "medium", "policy"],
  "POST /api/org/policy-drafts/preview": ["api_org", "api_org.post_org_policy_drafts_preview", "create", "medium", "policy"],
  "POST /api/org/sources": ["api_org", "api_org.post_org_sources", "create", "medium"],
  "POST /api/org/sources/:id/bake": ["api_org", "api_org.post_org_sources_item_bake", "create", "medium"],
  "POST /api/sessions": ["api_sessions", "api_sessions.post_sessions", "create", "medium", "session"],
  "POST /api/sessions/:id/auto-title": ["api_sessions", "api_sessions.post_sessions_item_auto_title", "create", "medium", "session"],
  "POST /api/sessions/:id/decisions/:gateId/resolve": ["api_sessions", "api_sessions.post_sessions_item_decisions_item_resolve", "approve", "high", "session"],
  "POST /api/sessions/:id/decisions/:gateId/withdraw": ["api_sessions", "api_sessions.post_sessions_item_decisions_item_withdraw", "cancel", "low", "session"],
  "POST /api/sessions/:id/files": ["api_sessions", "api_sessions.post_sessions_item_files", "create", "medium", "session"],
  "POST /api/sessions/:id/messages": ["api_sessions", "api_sessions.post_sessions_item_messages", "execute", "medium", "session"],
  "POST /api/sessions/:id/messages/:entryId/rating": ["api_sessions", "api_sessions.post_sessions_item_messages_item_rating", "create", "medium", "session"],
  "POST /api/sessions/:id/pause": ["api_sessions", "api_sessions.post_sessions_item_pause", "create", "medium", "session"],
  "POST /api/sessions/:id/rating": ["api_sessions", "api_sessions.post_sessions_item_rating", "create", "medium", "session"],
  "POST /api/sessions/:id/security/cancel": ["api_sessions", "api_sessions.post_sessions_item_security_cancel", "cancel", "low", "session"],
  "POST /api/sessions/:id/security/cells/:cellId/complete": ["api_sessions", "api_sessions.post_sessions_item_security_cells_item_complete", "create", "medium", "session"],
  "POST /api/sessions/:id/security/cells/:cellId/fail": ["api_sessions", "api_sessions.post_sessions_item_security_cells_item_fail", "create", "medium", "session"],
  "POST /api/sessions/:id/security/close": ["api_sessions", "api_sessions.post_sessions_item_security_close", "create", "medium", "session"],
  "POST /api/sessions/:id/security/config": ["api_sessions", "api_sessions.post_sessions_item_security_config", "create", "medium", "session"],
  "POST /api/sessions/:id/security/coverage": ["api_sessions", "api_sessions.post_sessions_item_security_coverage", "create", "medium", "session"],
  "POST /api/sessions/:id/security/dispatch": ["api_sessions", "api_sessions.post_sessions_item_security_dispatch", "create", "medium", "session"],
  "POST /api/sessions/:id/security/files": ["api_sessions", "api_sessions.post_sessions_item_security_files", "create", "medium", "session"],
  "POST /api/sessions/:id/security/findings": ["api_sessions", "api_sessions.post_sessions_item_security_findings", "create", "medium", "session"],
  "POST /api/sessions/:id/security/findings/:findingId/comments": ["api_sessions", "api_sessions.post_sessions_item_security_findings_item_comments", "create", "medium", "session"],
  "POST /api/sessions/:id/security/findings/:findingId/issues": ["api_sessions", "api_sessions.post_sessions_item_security_findings_item_issues", "create", "medium", "session"],
  "POST /api/sessions/:id/security/findings/:findingId/review": ["api_sessions", "api_sessions.post_sessions_item_security_findings_item_review", "create", "medium", "session"],
  "POST /api/sessions/:id/security/findings/:findingId/status": ["api_sessions", "api_sessions.post_sessions_item_security_findings_item_status", "create", "medium", "session"],
  "POST /api/sessions/:id/security/handoff": ["api_sessions", "api_sessions.post_sessions_item_security_handoff", "create", "medium", "session"],
  "POST /api/sessions/:id/security/issues/digest": ["api_sessions", "api_sessions.post_sessions_item_security_issues_digest", "create", "medium", "session"],
  "POST /api/sessions/:id/security/needs": ["api_sessions", "api_sessions.post_sessions_item_security_needs", "create", "medium", "session"],
  "POST /api/sessions/:id/security/needs/resolve": ["api_sessions", "api_sessions.post_sessions_item_security_needs_resolve", "approve", "high", "session"],
  "POST /api/sessions/:id/security/plan": ["api_sessions", "api_sessions.post_sessions_item_security_plan", "create", "medium", "session"],
  "POST /api/sessions/:id/security/plan/cells": ["api_sessions", "api_sessions.post_sessions_item_security_plan_cells", "create", "medium", "session"],
  "POST /api/sessions/:id/security/report": ["api_sessions", "api_sessions.post_sessions_item_security_report", "create", "medium", "repository"],
  "POST /api/sessions/:id/security/resume": ["api_sessions", "api_sessions.post_sessions_item_security_resume", "create", "medium", "session"],
  "POST /api/sessions/:id/security/start": ["api_sessions", "api_sessions.post_sessions_item_security_start", "execute", "medium", "session"],
  "POST /api/sessions/:id/threads": ["api_sessions", "api_sessions.post_sessions_item_threads", "create", "medium", "session"],
  "POST /api/sessions/:id/threads/:threadId/abort": ["api_sessions", "api_sessions.post_sessions_item_threads_item_abort", "cancel", "low", "session"],
  "POST /api/sessions/security/preview": ["api_sessions", "api_sessions.post_sessions_security_preview", "create", "medium", "session"],
  "POST /api/skills": ["api_skills", "api_skills.post_skills", "create", "medium"],
  "POST /api/skills/sources": ["api_skills", "api_skills.post_skills_sources", "create", "medium"],
  "POST /api/skills/sources/:id/sync": ["api_skills", "api_skills.post_skills_sources_item_sync", "create", "medium"],
  "POST /api/teams": ["api_teams", "api_teams.post_teams", "create", "medium", "team"],
  "POST /api/teams/:id/api-keys": ["api_teams", "api_teams.post_teams_item_api_keys", "create", "medium", "team"],
  "POST /api/teams/:id/deletion-requests": ["api_teams", "api_teams.post_teams_item_deletion_requests", "create", "medium", "team"],
  "POST /api/teams/:id/deletion-requests/:requestId/:decision": ["api_teams", "api_teams.post_teams_item_deletion_requests_item_item", "create", "medium", "team"],
  "POST /api/teams/:id/deletion-requests/*": ["api_teams", "api_teams.post_teams_item_deletion_requests_item", "create", "medium", "team"],
  "POST /api/teams/:id/join": ["api_teams", "api_teams.post_teams_item_join", "create", "medium", "team"],
  "POST /api/teams/:id/members": ["api_teams", "api_teams.post_teams_item_members", "create", "medium", "team"],
  "POST /api/teams/:id/orchestrator": ["api_teams", "api_teams.post_teams_item_orchestrator", "create", "medium", "team"],
  "POST /api/teams/:id/policies": ["api_teams", "api_teams.post_teams_item_policies", "create", "medium", "policy"],
  "POST /api/teams/:id/policies/:policyId": ["api_teams", "api_teams.post_teams_item_policies_item", "create", "medium", "policy"],
  "POST /api/teams/:teamId/policy-drafts": ["api_teams", "api_teams.post_teams_item_policy_drafts", "create", "medium", "policy"],
  "POST /api/teams/:teamId/policy-drafts/:documentId/prepare-publication": ["api_teams", "api_teams.post_teams_item_policy_drafts_item_prepare_publication", "create", "medium", "policy"],
  "POST /api/teams/:teamId/policy-drafts/:documentId/restore/:revision": ["api_teams", "api_teams.post_teams_item_policy_drafts_item_restore_item", "create", "medium", "policy"],
  "POST /api/teams/:teamId/policy-drafts/:documentId/reviews": ["api_teams", "api_teams.post_teams_item_policy_drafts_item_reviews", "approve", "high", "policy"],
  "POST /api/teams/:teamId/policy-drafts/:documentId/submit-review": ["api_teams", "api_teams.post_teams_item_policy_drafts_item_submit_review", "create", "medium", "policy"],
  "POST /api/teams/:teamId/policy-drafts/preview": ["api_teams", "api_teams.post_teams_item_policy_drafts_preview", "create", "medium", "policy"],
  "POST /api/templates/:id/install": ["api_templates", "api_templates.post_templates_item_install", "create", "medium"],
  "POST /api/workflows": ["api_workflows", "api_workflows.post_workflows", "create", "medium", "workflow"],
  "POST /api/workflows/:id/copy": ["api_workflows", "api_workflows.post_workflows_item_copy", "copy", "low", "workflow"],
  "POST /api/workflows/:id/copy-to-team": ["api_workflows", "api_workflows.post_workflows_item_copy_to_team", "copy", "low", "workflow"],
  "POST /api/workflows/:id/permissions/allow": ["api_workflows", "api_workflows.post_workflows_item_permissions_allow", "create", "medium", "workflow"],
  "POST /api/workflows/:id/preview": ["api_workflows", "api_workflows.post_workflows_item_preview", "create", "medium", "workflow"],
  "POST /api/workflows/:id/runs": ["api_workflows", "api_workflows.post_workflows_item_runs", "execute", "medium", "workflow"],
  "POST /api/workflows/:id/schedules": ["api_workflows", "api_workflows.post_workflows_item_schedules", "create", "medium", "workflow"],
  "POST /api/workflows/:id/webhook": ["api_workflows", "api_workflows.post_workflows_item_webhook", "create", "medium", "workflow"],
  "POST /api/workflows/event-triggers": ["api_workflows", "api_workflows.post_workflows_event_triggers", "create", "medium", "workflow"],
  "POST /api/workflows/runs/:runId/approvals/:nodeId": ["api_workflows", "api_workflows.post_workflows_runs_item_approvals_item", "execute", "medium", "workflow"],
  "POST /api/workflows/runs/:runId/cancel": ["api_workflows", "api_workflows.post_workflows_runs_item_cancel", "cancel", "low", "workflow"],
  "POST /api/workflows/runs/:runId/retry": ["api_workflows", "api_workflows.post_workflows_runs_item_retry", "execute", "medium", "workflow"],
  "POST /api/workflows/schedules": ["api_workflows", "api_workflows.post_workflows_schedules", "create", "medium", "workflow"],
  "POST /api/workflows/schedules/:id/run": ["api_workflows", "api_workflows.post_workflows_schedules_item_run", "execute", "medium", "workflow"],
  "PUT /api/admin/*": ["api_admin", "api_admin.put_admin_item", "update", "medium"],
  "PUT /api/me/policy-overrides": ["api_me", "api_me.put_me_policy_overrides", "update", "medium", "policy"],
  "PUT /api/notifications/preferences": ["api_notifications", "api_notifications.put_notifications_preferences", "update", "medium"],
  "PUT /api/org/approved-models": ["api_org", "api_org.put_org_approved_models", "approve", "high"],
  "PUT /api/proxy/settings": ["api_proxy", "api_proxy.put_proxy_settings", "update", "medium"],
  "PUT /api/teams/:id/deletion-requests/*": ["api_teams", "api_teams.put_teams_item_deletion_requests_item", "update", "medium", "team"],
  "PUT /api/teams/:id/grants/:grantId": ["api_teams", "api_teams.put_teams_item_grants_item", "update", "medium", "policy"],
  "PUT /api/teams/:id/policy-overrides": ["api_teams", "api_teams.put_teams_item_policy_overrides", "update", "medium", "policy"],
  "PUT /api/workflows/:id": ["api_workflows", "api_workflows.put_workflows_item", "update", "medium", "workflow"],
});
export const WS_OPERATION_DESCRIPTOR_SEEDS_V1: Readonly<Record<string, Seed>> = Object.freeze({
  "session.stream.connect": ["api_sessions", "api_sessions.get_sessions_item_ws", "read", "low", "session"],
  "session.stream.subscribe": ["api_sessions", "api_sessions.ws_subscribe", "read", "low", "session"],
  "session.stream.pong": ["api_sessions", "api_sessions.ws_pong", "update", "low", "session"],
});

export const ROUTE_BOUNDARY_EXCLUSIONS_V1: readonly BoundaryExclusionV1[] = Object.freeze([
  { schemaVersion: 1, key: "GET /api/health", classification: "public", rationale: "Health probes must run before authentication." },
  { schemaVersion: 1, key: "GET /api/ready", classification: "public", rationale: "Readiness probes must run before authentication." },
  { schemaVersion: 1, key: "GET /api/auth-config", classification: "public", rationale: "The login page needs authentication configuration." },
  { schemaVersion: 1, key: "ALL /api/auth/*", classification: "public", rationale: "The authentication provider owns login and callbacks." },
  { schemaVersion: 1, key: "POST /api/channels/slack/webhook", classification: "public", rationale: "The Slack signature verifier owns this public ingress." },
  { schemaVersion: 1, key: "POST /api/channels/:channelType/webhook", classification: "public", rationale: "The channel transport verifier owns this public ingress." },
  { schemaVersion: 1, key: "POST /webhooks/github-app", classification: "public", rationale: "The GitHub signature verifier owns this public ingress." },
  { schemaVersion: 1, key: "POST /webhooks/events/:service", classification: "public", rationale: "The plugin signature verifier owns this public ingress." },
  { schemaVersion: 1, key: "POST /api/hooks/workflows/:workflowId/:hookId", classification: "public", rationale: "The workflow hook capability and rate limit own this public ingress." },
  { schemaVersion: 1, key: "GET /api/artifacts/:token", classification: "public", rationale: "The artifact capability token owns this public read." },
  { schemaVersion: 1, key: "GET /api/artifacts/:token/comments", classification: "public", rationale: "The artifact capability route resolves optional identity itself." },
  { schemaVersion: 1, key: "POST /api/artifacts/:token/comments", classification: "public", rationale: "The artifact capability route resolves identity before comment writes." },
  { schemaVersion: 1, key: "POST /api/artifacts/:token/comments/:commentId/resolve", classification: "public", rationale: "The artifact capability route resolves identity before comment writes." },
  { schemaVersion: 1, key: "GET /avatars/:kind/:filename", classification: "public", rationale: "Public assistant icons are static content." },
  { schemaVersion: 1, key: "GET /*", classification: "public", rationale: "The static web fallback contains no API data." },
  { schemaVersion: 1, key: "DELETE /api/credentials/:service", classification: "pr12_owned", rationale: "PR 12 owns sandbox, memory, or credential authorization for this boundary." },
  { schemaVersion: 1, key: "DELETE /api/credentials/:service/delegations/:teamId", classification: "pr12_owned", rationale: "PR 12 owns sandbox, memory, or credential authorization for this boundary." },
  { schemaVersion: 1, key: "DELETE /api/memory", classification: "pr12_owned", rationale: "PR 12 owns sandbox, memory, or credential authorization for this boundary." },
  { schemaVersion: 1, key: "DELETE /api/org/llm-providers/:id", classification: "pr12_owned", rationale: "PR 12 owns sandbox, memory, or credential authorization for this boundary." },
  { schemaVersion: 1, key: "DELETE /api/org/llm-providers/:id/key", classification: "pr12_owned", rationale: "PR 12 owns sandbox, memory, or credential authorization for this boundary." },
  { schemaVersion: 1, key: "DELETE /api/sessions/:id/gateway/*", classification: "pr12_owned", rationale: "PR 12 owns sandbox, memory, or credential authorization for this boundary." },
  { schemaVersion: 1, key: "GET /api/credentials", classification: "pr12_owned", rationale: "PR 12 owns sandbox, memory, or credential authorization for this boundary." },
  { schemaVersion: 1, key: "GET /api/credentials/:service/connect", classification: "pr12_owned", rationale: "PR 12 owns sandbox, memory, or credential authorization for this boundary." },
  { schemaVersion: 1, key: "GET /api/credentials/oauth/callback", classification: "pr12_owned", rationale: "PR 12 owns sandbox, memory, or credential authorization for this boundary." },
  { schemaVersion: 1, key: "GET /api/memory", classification: "pr12_owned", rationale: "PR 12 owns sandbox, memory, or credential authorization for this boundary." },
  { schemaVersion: 1, key: "GET /api/memory/export", classification: "pr12_owned", rationale: "PR 12 owns sandbox, memory, or credential authorization for this boundary." },
  { schemaVersion: 1, key: "GET /api/memory/graph", classification: "pr12_owned", rationale: "PR 12 owns sandbox, memory, or credential authorization for this boundary." },
  { schemaVersion: 1, key: "GET /api/memory/journal-summary", classification: "pr12_owned", rationale: "PR 12 owns sandbox, memory, or credential authorization for this boundary." },
  { schemaVersion: 1, key: "GET /api/memory/links", classification: "pr12_owned", rationale: "PR 12 owns sandbox, memory, or credential authorization for this boundary." },
  { schemaVersion: 1, key: "GET /api/memory/search", classification: "pr12_owned", rationale: "PR 12 owns sandbox, memory, or credential authorization for this boundary." },
  { schemaVersion: 1, key: "GET /api/memory/tree", classification: "pr12_owned", rationale: "PR 12 owns sandbox, memory, or credential authorization for this boundary." },
  { schemaVersion: 1, key: "GET /api/onepassword/settings", classification: "pr12_owned", rationale: "PR 12 owns sandbox, memory, or credential authorization for this boundary." },
  { schemaVersion: 1, key: "GET /api/onepassword/team-status", classification: "pr12_owned", rationale: "PR 12 owns sandbox, memory, or credential authorization for this boundary." },
  { schemaVersion: 1, key: "GET /api/onepassword/vaults", classification: "pr12_owned", rationale: "PR 12 owns sandbox, memory, or credential authorization for this boundary." },
  { schemaVersion: 1, key: "GET /api/org/llm-providers", classification: "pr12_owned", rationale: "PR 12 owns sandbox, memory, or credential authorization for this boundary." },
  { schemaVersion: 1, key: "GET /api/org/llm-providers/openrouter/models", classification: "pr12_owned", rationale: "PR 12 owns sandbox, memory, or credential authorization for this boundary." },
  { schemaVersion: 1, key: "GET /api/sessions/:id/gateway/*", classification: "pr12_owned", rationale: "PR 12 owns sandbox, memory, or credential authorization for this boundary." },
  { schemaVersion: 1, key: "HEAD /api/sessions/:id/gateway/*", classification: "pr12_owned", rationale: "PR 12 owns sandbox, memory, or credential authorization for this boundary." },
  { schemaVersion: 1, key: "OPTIONS /api/sessions/:id/gateway/*", classification: "pr12_owned", rationale: "PR 12 owns sandbox, memory, or credential authorization for this boundary." },
  { schemaVersion: 1, key: "PATCH /api/org/llm-providers/:id", classification: "pr12_owned", rationale: "PR 12 owns sandbox, memory, or credential authorization for this boundary." },
  { schemaVersion: 1, key: "PATCH /api/sessions/:id/gateway/*", classification: "pr12_owned", rationale: "PR 12 owns sandbox, memory, or credential authorization for this boundary." },
  { schemaVersion: 1, key: "POST /api/credentials/:service/delegate", classification: "pr12_owned", rationale: "PR 12 owns sandbox, memory, or credential authorization for this boundary." },
  { schemaVersion: 1, key: "POST /api/memory/copy-from-team", classification: "pr12_owned", rationale: "PR 12 owns sandbox, memory, or credential authorization for this boundary." },
  { schemaVersion: 1, key: "POST /api/memory/copy-to-team", classification: "pr12_owned", rationale: "PR 12 owns sandbox, memory, or credential authorization for this boundary." },
  { schemaVersion: 1, key: "POST /api/memory/import", classification: "pr12_owned", rationale: "PR 12 owns sandbox, memory, or credential authorization for this boundary." },
  { schemaVersion: 1, key: "POST /api/memory/move", classification: "pr12_owned", rationale: "PR 12 owns sandbox, memory, or credential authorization for this boundary." },
  { schemaVersion: 1, key: "POST /api/memory/patch", classification: "pr12_owned", rationale: "PR 12 owns sandbox, memory, or credential authorization for this boundary." },
  { schemaVersion: 1, key: "POST /api/org/llm-providers", classification: "pr12_owned", rationale: "PR 12 owns sandbox, memory, or credential authorization for this boundary." },
  { schemaVersion: 1, key: "POST /api/org/llm-providers/:id/probe", classification: "pr12_owned", rationale: "PR 12 owns sandbox, memory, or credential authorization for this boundary." },
  { schemaVersion: 1, key: "POST /api/org/llm-providers/:id/test", classification: "pr12_owned", rationale: "PR 12 owns sandbox, memory, or credential authorization for this boundary." },
  { schemaVersion: 1, key: "POST /api/sandbox-secrets/find", classification: "pr12_owned", rationale: "PR 12 owns sandbox, memory, or credential authorization for this boundary." },
  { schemaVersion: 1, key: "POST /api/sandbox-secrets/resolve", classification: "pr12_owned", rationale: "PR 12 owns sandbox, memory, or credential authorization for this boundary." },
  { schemaVersion: 1, key: "POST /api/sandbox/git-credential", classification: "pr12_owned", rationale: "PR 12 owns sandbox, memory, or credential authorization for this boundary." },
  { schemaVersion: 1, key: "POST /api/sessions/:id/gateway/*", classification: "pr12_owned", rationale: "PR 12 owns sandbox, memory, or credential authorization for this boundary." },
  { schemaVersion: 1, key: "POST /api/sessions/:id/sandbox-jwt", classification: "pr12_owned", rationale: "PR 12 owns sandbox, memory, or credential authorization for this boundary." },
  { schemaVersion: 1, key: "POST /api/sessions/:id/sandbox/replace", classification: "pr12_owned", rationale: "PR 12 owns sandbox, memory, or credential authorization for this boundary." },
  { schemaVersion: 1, key: "PUT /api/credentials/:service", classification: "pr12_owned", rationale: "PR 12 owns sandbox, memory, or credential authorization for this boundary." },
  { schemaVersion: 1, key: "PUT /api/memory", classification: "pr12_owned", rationale: "PR 12 owns sandbox, memory, or credential authorization for this boundary." },
  { schemaVersion: 1, key: "PUT /api/onepassword/settings", classification: "pr12_owned", rationale: "PR 12 owns sandbox, memory, or credential authorization for this boundary." },
  { schemaVersion: 1, key: "PUT /api/org/llm-providers/:id/key", classification: "pr12_owned", rationale: "PR 12 owns sandbox, memory, or credential authorization for this boundary." },
  { schemaVersion: 1, key: "PUT /api/sessions/:id/gateway/*", classification: "pr12_owned", rationale: "PR 12 owns sandbox, memory, or credential authorization for this boundary." },
]);
const HTTP_METHODS = ["GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS", "HEAD"] as const;
const protectedExclusions = new Set(ROUTE_BOUNDARY_EXCLUSIONS_V1.filter((entry) => entry.classification === "pr12_owned").map((entry) => entry.key));
export function buildApiRouteRegistry(routes: readonly Pick<RouterRoute, "method" | "path">[]): readonly ApiRouteDescriptorV1[] {
  const actual = new Set<string>();
  for (const route of routes) for (const method of route.method === "ALL" ? HTTP_METHODS : [route.method.toUpperCase()]) actual.add(`${method} ${canonicalTemplate(route.path)}`);
  const expected = new Set([...Object.keys(API_ROUTE_DESCRIPTOR_SEEDS_V1), ...protectedExclusions]);
  const missing = [...expected].filter((key) => !actual.has(key)); const unknown = [...actual].filter((key) => !expected.has(key));
  if (missing.length || unknown.length) throw new Error(`Protected route inventory mismatch. Missing: ${missing.join(", ") || "none"}. Unknown: ${unknown.join(", ") || "none"}.`);
  return Object.freeze(Object.entries(API_ROUTE_DESCRIPTOR_SEEDS_V1).map(([key, seed]) => {
    const split = key.indexOf(" ");
    const method = key.slice(0, split), template = key.slice(split + 1);
    const [service, actionId, operation, riskLevel, resourceKind] = seed;
    const group = service.slice(4);
    return Object.freeze({
      schemaVersion: 1 as const, method, template, service, actionId, operation, riskLevel,
      safeProjection: SAFE_ROUTE_PROJECTIONS_V1[key] ?? (method === "DELETE" ? { kind: "no_body" as const } : { kind: "unsupported" as const }),
      approvalSupported: (SAFE_ROUTE_PROJECTIONS_V1[key] !== undefined || method === "DELETE"),
      obligations: [] as const, audit: { group },
      ...(resourceKind === undefined ? {} : { resourceKind }),
    });
  }).sort((a, b) => `${a.method} ${a.template}`.localeCompare(`${b.method} ${b.template}`)));
}
export function isProtectedBoundaryExclusion(method: string, path: string): boolean {
  const actualMethod = method.toUpperCase();
  return ROUTE_BOUNDARY_EXCLUSIONS_V1.some((entry) => {
    if (entry.classification !== "pr12_owned") return false;
    const split = entry.key.indexOf(" ");
    const expectedMethod = entry.key.slice(0, split);
    return (expectedMethod === "ALL" || expectedMethod === actualMethod) && templateMatches(entry.key.slice(split + 1), path);
  });
}
function templateMatches(template: string, path: string): boolean {
  const expected = canonicalTemplate(template).split("/").filter(Boolean);
  const actual = canonicalTemplate(path).split("/").filter(Boolean);
  if (expected.at(-1) !== "*" && expected.length !== actual.length) return false;
  if (expected.at(-1) === "*" && actual.length < expected.length - 1) return false;
  return expected.every((part, index) => part === "*" || part.startsWith(":") || part === actual[index]);
}
function canonicalTemplate(path: string): string { const value = path.replace(/\/+/g, "/"); return value.length > 1 && value.endsWith("/") ? value.slice(0, -1) : value; }
