import { Type } from "typebox";
import { createAssistantMessageEventStream, type AssistantMessage, type SimpleStreamOptions, type Message, type Model, type Api } from "@earendil-works/pi-ai";
import { streamSimple } from "@earendil-works/pi-ai/compat";
import { supportsNativeImageGeneration } from "./model-catalog.js";
import { decodeImageBase64, imageAttachment, imageDecoder, validateImage, IMAGE_FORMATS, MAX_IMAGE_BYTES } from "./image-output.js";
import type { Sandbox, ToolDef, ToolResult } from "./types.js";

export const NATIVE_IMAGE_RESULT_TOOL = "openai_native_image";
const DUPLICATE_TOOLS = new Set(["openai__generate_image"]);
const NATIVE_PATH = /^generated-images\/[a-f0-9-]+\.(png|jpg|webp)$/;

function record(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

/** One thread owns this bridge. The engine stores its results through ordinary tool persistence. */
export class NativeImageBridge {
  private saved = new Map<string, ToolResult>();

  tool(): ToolDef {
    return {
      name: NATIVE_IMAGE_RESULT_TOOL,
      description: "Internal receipt for an image generated by the session model. Never call this tool yourself.",
      parameters: Type.Object({ path: Type.String(), image_id: Type.String() }),
      protectedFromPruning: true,
      execute: async (args, ctx) => {
        ctx.signal.throwIfAborted();
        if (!record(args) || typeof args.path !== "string" || !NATIVE_PATH.test(args.path) || typeof args.image_id !== "string") {
          throw new Error("Invalid native image receipt. Request the image again.");
        }
        const key = `${args.image_id}:${args.path}`;
        const saved = this.saved.get(key);
        if (saved) { this.saved.delete(key); return saved; }
        // An interrupted turn can replay its receipt after restart. Never regenerate or pay again.
        const stat = await ctx.sandbox.stat(args.path);
        if (!stat.isFile || stat.size > MAX_IMAGE_BYTES) throw new Error("The saved native image is unavailable. Request it again.");
        const bytes = await ctx.sandbox.readBinary(args.path);
        return this.result(bytes, args.path, args.image_id, ctx.signal);
      },
    };
  }

  private async result(bytes: Uint8Array, path: string, id: string, signal?: AbortSignal): Promise<ToolResult> {
    const sharp = await imageDecoder();
    const format = await validateImage(bytes, sharp);
    if (format !== "png" && format !== "jpeg" && format !== "webp") throw new Error("Unsupported image format. Request PNG, JPEG, or WebP.");
    if (path.slice(path.lastIndexOf(".")) !== `.${IMAGE_FORMATS[format].ext}`) throw new Error("The saved image format differs from its filename. Request the image again.");
    const preview = await imageAttachment(bytes, format, sharp);
    signal?.throwIfAborted();
    return {
      text: JSON.stringify({ path, bytes: bytes.byteLength, mimeType: IMAGE_FORMATS[format].mime, image_id: id, model: "gpt-image-2.5-sunburst" }),
      attachments: [{ type: "image", data: preview, mimeType: IMAGE_FORMATS[format].mime, name: path.slice(path.lastIndexOf("/") + 1) }],
    };
  }

  stream(model: Model<Api>, context: { messages: Message[] }, options: SimpleStreamOptions, sandbox: Sandbox, enabled = true) {
    this.saved.clear();
    const native = enabled && supportsNativeImageGeneration(model);
    // Execution-only receipts are never advertised to any model. Native models also lose pinned duplicates.
    const hidden = (name: string) => name === NATIVE_IMAGE_RESULT_TOOL || (native && DUPLICATE_TOOLS.has(name));
    const transcript: { messages: Message[] } = { messages: context.messages.map((message) => message.role === "system"
      ? { ...message, toolsAdded: message.toolsAdded?.filter((tool) => !hidden(tool.name)), toolsRemoved: message.toolsRemoved?.filter((tool) => !hidden(tool.name)) }
      : message) };
    if (!native) return streamSimple(model, transcript, options);

    const output = createAssistantMessageEventStream();
    const receipts: Array<{ path: string; image_id: string }> = [];
    const seen = new Map<string, string>();
    let partial: AssistantMessage | undefined;
    const capture = async (item: unknown) => {
      if (!record(item) || item.type !== "image_generation_call") return;
      if (item.status !== "completed" || typeof item.id !== "string" || !item.id || item.id.length > 200) {
        throw new Error("OpenAI did not complete the image. Request it again with a simpler prompt.");
      }
      const bytes = decodeImageBase64(item.result);
      const hash = Array.from(new Uint8Array(await crypto.subtle.digest("SHA-256", new Uint8Array(bytes))), (byte) => byte.toString(16).padStart(2, "0")).join("");
      if (seen.has(item.id)) {
        if (seen.get(item.id) !== hash) throw new Error("OpenAI returned conflicting image results. Request the image again.");
        return;
      }
      const sharp = await imageDecoder();
      const format = await validateImage(bytes, sharp);
      if (format !== "png" && format !== "jpeg" && format !== "webp") throw new Error("Unsupported image format. Request PNG, JPEG, or WebP.");
      if (item.output_format != null && item.output_format !== format) throw new Error("OpenAI returned a mismatched image format. Request the image again.");
      const path = `generated-images/${crypto.randomUUID()}.${IMAGE_FORMATS[format].ext}`;
      const result = await this.result(bytes, path, item.id, options.signal);
      options.signal?.throwIfAborted();
      try {
        await sandbox.mkdir("generated-images");
        options.signal?.throwIfAborted();
        await sandbox.writeBinary(path, bytes);
      } catch { options.signal?.throwIfAborted(); throw new Error("Cannot save the generated image. Check the sandbox storage and request it again."); }
      options.signal?.throwIfAborted();
      this.saved.set(`${item.id}:${path}`, result);
      seen.set(item.id, hash);
      receipts.push({ path, image_id: item.id });
    };
    const upstream = streamSimple(model, transcript, {
      ...options,
      onPayload: async (payload, requestModel) => {
        const transformed = (await options.onPayload?.(payload, requestModel)) ?? payload;
        if (!record(transformed)) throw new Error("Invalid Responses payload. Restart this turn.");
        // Fail before any paid request if native image decoding is unavailable.
        await imageDecoder();
        return { ...transformed, tools: [...(Array.isArray(transformed.tools) ? transformed.tools : []),
          { type: "image_generation", model: "gpt-image-2.5-sunburst", output_format: "png", quality: "auto" }] };
      },
      onProviderStreamEvent: async (event, requestModel) => {
        await options.onProviderStreamEvent?.(event, requestModel);
        if (!record(event)) return;
        if (event.type === "response.output_item.done") await capture(event.item);
        if (event.type === "response.completed" && record(event.response) && Array.isArray(event.response.output)) {
          for (const item of event.response.output) await capture(item);
        }
      },
    });
    void (async () => {
      try {
        for await (const event of upstream) {
          if ("partial" in event) partial = event.partial;
          if (event.type === "done" && receipts.length) {
            options.signal?.throwIfAborted();
            for (const receipt of receipts) {
              const toolCall = { type: "toolCall" as const, id: `call_${crypto.randomUUID().replaceAll("-", "")}`, name: NATIVE_IMAGE_RESULT_TOOL, arguments: receipt };
              const contentIndex = event.message.content.length;
              event.message.content.push(toolCall);
              output.push({ type: "toolcall_start", contentIndex, partial: event.message });
              output.push({ type: "toolcall_end", contentIndex, toolCall, partial: event.message });
            }
            event.message.stopReason = "toolUse";
            output.push({ type: "done", reason: "toolUse", message: event.message });
          } else output.push(event);
        }
      } catch (error) {
        if (partial) output.push({ type: "error", reason: options.signal?.aborted ? "aborted" : "error",
          error: { ...partial, stopReason: options.signal?.aborted ? "aborted" : "error", errorMessage: error instanceof Error ? error.message : "Image delivery failed. Request the image again." } });
      } finally {
        output.end();
        seen.clear();
      }
    })();
    return output;
  }
}
