/**
 * `valet-sign` — git's SSH signing program in a sandbox
 * (`docs/specs/2026-09-12-agent-commit-signing-design.md`).
 *
 * Git calls it as `valet-sign -Y sign -n git -f <pubkey-file> [-U] <payload>`,
 * and for `git verify-commit` and `git log --show-signature` as `-Y
 * find-principals` and `-Y check-novalidate`; those are handed to ssh-keygen.
 * The script exports the session's `TURNKEY_*` bundle from the env file the
 * prep step wrote, adds the API key pair from the session key file, and execs
 * `tk ssh git-sign` with git's arguments. `tk` signs through Turnkey; no
 * private key is on the runner.
 *
 * Deterministic text (no timestamps, no randomness): sandbox-spec hashes it
 * into the `credential-scripts` step, so an edit here re-installs on every
 * sandbox that already ran prep. No secret or token material is embedded.
 */
import { ENV_FILE, PRIVATE_KEY_ID_VAR, SESSION_KEY_FILE, TK_PATH } from "@valet/plugin-turnkey/sandbox";

export function valetSignScript(): string {
  return `#!/bin/sh
# valet-sign — git's gpg.ssh.program. Signs through Turnkey with tk; no
# private key is in this sandbox. Generated by @valet/api
# (engine/commit-signing-script.ts); installed by sandbox prep.
set -eu

# Git uses this program to verify too (-Y find-principals, check-novalidate,
# verify). Those need no key and belong to the real ssh-keygen; only -Y sign
# goes through Turnkey.
case "$*" in
  *"-Y sign"*) ;;
  *) exec ssh-keygen "$@" ;;
esac

ENV_FILE="${ENV_FILE}"
KEY_FILE="${SESSION_KEY_FILE}"
TK="${TK_PATH}"

if [ ! -x "$TK" ]; then
  echo "valet-sign: tk is not installed in this sandbox image. Commit with --no-gpg-sign, and report this to an admin." >&2
  exit 1
fi
if [ ! -f "$ENV_FILE" ] || [ ! -f "$KEY_FILE" ]; then
  echo "valet-sign: this session has no Turnkey session key. Set up commit signing under Settings, Connected accounts, then start a new session. Or commit with --no-gpg-sign." >&2
  exit 1
fi

set -a
. "$ENV_FILE"
set +a

if [ -z "\${${PRIVATE_KEY_ID_VAR}:-}" ]; then
  echo "valet-sign: no signing key for this session. Call turnkey.request_signing_key first, or commit with --no-gpg-sign." >&2
  exit 1
fi

# The session key file is tk's own api-key format: {"public_key":..,"private_key":..}.
TURNKEY_API_PUBLIC_KEY=$(sed -n 's/.*"public_key"[[:space:]]*:[[:space:]]*"\\([0-9a-fA-F]*\\)".*/\\1/p' "$KEY_FILE")
TURNKEY_API_PRIVATE_KEY=$(sed -n 's/.*"private_key"[[:space:]]*:[[:space:]]*"\\([0-9a-fA-F]*\\)".*/\\1/p' "$KEY_FILE")
export TURNKEY_API_PUBLIC_KEY TURNKEY_API_PRIVATE_KEY
if [ -z "$TURNKEY_API_PUBLIC_KEY" ] || [ -z "$TURNKEY_API_PRIVATE_KEY" ]; then
  echo "valet-sign: the session key file is unreadable. Start a new session." >&2
  exit 1
fi

# tk exits non-zero with the activity id when Turnkey parks the signature
# for approval, and with Turnkey's message when the session key expired.
# Both reach git's stderr unchanged; git then fails the commit.
exec "$TK" ssh git-sign "$@"
`;
}
