/**
 * In-sandbox git credential surface — pure script-text generators
 * (GitHub/repo integration plan, Task 8). These produce POSIX `sh` scripts
 * that sandbox prep (Task 9) writes to disk and wires into git / `gh`. They
 * are unit-tested against goldens; keep them deterministic (no timestamps,
 * no randomness) so the goldens stay stable.
 *
 * ── Security invariants (pinned by the golden tests) ─────────────────────
 *   - NO token material is ever embedded in the generated text. The sandbox
 *     token is read at call time: first from `/etc/valet/creds/token` (the
 *     creds volume mount Task 10 provisions), then from the
 *     `$VALET_SANDBOX_TOKEN` environment variable as a fallback (every
 *     sandbox already has it — see `engine/host.ts`'s `mintSandboxEnv`).
 *     The only interpolated value is `apiUrl`, which is not secret.
 *   - The scripts authenticate to the API with the `x-valet-sandbox` header
 *     — the same header `middleware/auth.ts`'s sandbox rung verifies. (The
 *     task brief floated `Authorization: Bearer`, but the middleware only
 *     reads `x-valet-sandbox`; the middleware is ground truth.)
 *
 * ── Why `#!/bin/sh` and not bash ─────────────────────────────────────────
 * The sandbox images ship bash, but nothing here needs a bashism, so the
 * scripts target plain POSIX `sh` for portability. Response parsing uses
 * `sed` (GitHub tokens and the `x-access-token` username contain no `"` or
 * `\`, so a `"\([^"]*\)"` capture is safe) rather than assuming `jq`.
 */

/** Path (relative to the API base) of the credential-minting route. */
const ROUTE_PATH = "/api/sandbox/git-credential";

/** Preserved image Git binary. Generated wrappers never guess an image path. */
export const REAL_GIT_PATH = "/usr/local/lib/valet/git-real";

/**
 * The sandbox token, read at call time: the creds mount first (rotated in
 * place on backends that have one), then `$VALET_SANDBOX_TOKEN`. Every
 * generated in-sandbox script reads it this way, so it is written once.
 * Leaves `tok` set; empty when neither source has a token.
 */
export const SANDBOX_TOKEN_READ_SH = `tok=$(cat /etc/valet/creds/token 2>/dev/null) || tok=
[ -n "$tok" ] || tok=\${VALET_SANDBOX_TOKEN:-}`;

/**
 * `git-credential-valet` — a git credential helper (see `gitcredentials(7)`).
 *
 * git invokes it as `helper <verb>` and pipes the request attributes
 * (`protocol=`, `host=`, and — ONLY when `credential.useHttpPath` is true —
 * `path=`) on stdin, one `key=value` per line, terminated by a blank line.
 * HARD PREREQUISITE: git does NOT send `path=` by default, and this helper
 * derives `owner` from it — workspace prep MUST run
 * `git config --global credential.useHttpPath true` in the sandbox or the
 * helper exits silently and every clone runs anonymous. Only the `get` verb
 * does work; `store` and `erase` are no-ops (exit 0). On `get` we:
 *   1. parse `host` and `path` from stdin,
 *   2. derive `owner` as the first path segment (`owner/repo.git` → `owner`)
 *      and `repo` as the second (`.git` stripped; empty when git sent no repo
 *      segment) — `repo` lets the route pick the right binding when a session
 *      has two repos under one owner with different auth,
 *   3. POST `{host, owner, repo}` to the credential route with the sandbox token,
 *   4. emit `username=`/`password=` lines when the API returns a credential,
 *      or nothing (letting git proceed unauthenticated) on `{anonymous:true}`,
 *      an HTTP error (403 unbound / 409 credential-unavailable), a network
 *      failure, or a missing token.
 */
export function gitCredentialHelperScript(apiUrl: string): string {
  const url = `${apiUrl}${ROUTE_PATH}`;
  return `#!/bin/sh
# git-credential-valet — resolves a per-owner git token from the Valet API.
# Generated by @valet/api (engine/git-credential-helper.ts); installed by
# sandbox prep. Only the 'get' verb does work; 'store'/'erase' are no-ops.
# No token material is embedded here: the sandbox token is read from the
# creds mount (/etc/valet/creds/token) first, then \$VALET_SANDBOX_TOKEN.
set -eu

[ "\${1:-}" = "get" ] || exit 0

host=
path=
while IFS='=' read -r key value; do
  case "\$key" in
    host) host=\$value ;;
    path) path=\$value ;;
  esac
done

owner=\${path%%/*}
repo=
case "\$path" in
  */*) repo=\${path#*/}; repo=\${repo%%/*}; repo=\${repo%.git} ;;
esac
[ -n "\$owner" ] || exit 0
${SANDBOX_TOKEN_READ_SH}
# Degraded paths warn on stderr (git shows credential-helper stderr) but
# still exit 0 so PUBLIC repos keep working anonymously. Without the
# warning, a revoked/missing sandbox token surfaces only as a cryptic
# "unable to read <sha>" when a blobless clone lazily fetches blobs.
if [ -z "\$tok" ]; then
  echo "git-credential-valet: no sandbox token found — using no credentials for \$host/\$owner. If this repository needs auth, restart the session." >&2
  exit 0
fi

resp=\$(curl --max-time 10 -fsS \\
  -X POST "${url}" \\
  -H "x-valet-sandbox: \$tok" \\
  -H "Content-Type: application/json" \\
  -d "{\\"host\\":\\"\$host\\",\\"owner\\":\\"\$owner\\",\\"repo\\":\\"\$repo\\"}") || {
  echo "git-credential-valet: credential request to the Valet API failed — using no credentials for \$host/\$owner. If git then fails to fetch, restart the session to refresh sandbox credentials." >&2
  exit 0
}

username=\$(printf '%s' "\$resp" | sed -n 's/.*"username"[[:space:]]*:[[:space:]]*"\\([^"]*\\)".*/\\1/p')
password=\$(printf '%s' "\$resp" | sed -n 's/.*"password"[[:space:]]*:[[:space:]]*"\\([^"]*\\)".*/\\1/p')

[ -n "\$username" ] || exit 0
[ -n "\$password" ] || exit 0

printf 'username=%s\\n' "\$username"
printf 'password=%s\\n' "\$password"
`;
}

/**
 * The `gh` PATH shim (also kept at its historical `valet-gh` name) — injects
 * a Valet-resolved `GH_TOKEN` when the caller has not brought auth of their
 * own, then execs the REAL `gh` with the arguments unchanged.
 *
 * Sandbox prep installs this at `/usr/local/bin/gh`, which shadows the
 * image's `/usr/bin/gh` on PATH — so a plain `gh pr list` transparently
 * authenticates without the agent knowing the shim exists. The real binary
 * is located by scanning PATH and skipping `/usr/local/bin` (the shim's own
 * fixed install dir), which also makes the script safe to run under the
 * `valet-gh` name.
 *
 * Caller auth always wins: a set `GH_TOKEN`/`GITHUB_TOKEN` or a completed
 * `gh auth login` (hosts.yml present) short-circuits straight to the real
 * `gh` — the shim never overrides credentials the user chose.
 *
 * The owner/repo hint comes from the current repo's `origin` remote when
 * there is one; outside a repo the request is sent ownerless and the
 * credential route falls back to org-level resolution (`purpose: "api"`,
 * so a sole App installation still yields a token). The token fetch is
 * strictly best-effort and never blocks the command. No token material is
 * embedded; the sandbox token is read from the creds mount
 * (`/etc/valet/creds/token`) first, then from `$VALET_SANDBOX_TOKEN`.
 */
export function ghWrapperScript(apiUrl: string): string {
  const url = `${apiUrl}${ROUTE_PATH}`;
  return `#!/bin/sh
# gh (Valet shim, also installed as valet-gh) — runs the real 'gh' with a
# Valet-resolved GH_TOKEN when you have not authenticated yourself; your own
# GH_TOKEN/GITHUB_TOKEN or 'gh auth login' always wins. Generated by
# @valet/api (engine/git-credential-helper.ts); installed by sandbox prep.
# No token material is embedded here: the sandbox token is read from the
# creds mount (/etc/valet/creds/token) first, then \$VALET_SANDBOX_TOKEN.
set -u

# The real gh: first executable named 'gh' on PATH outside /usr/local/bin
# (this shim's fixed install dir — skipping it prevents self-exec).
real=
oldifs=\$IFS
IFS=:
for d in \$PATH; do
  case "\$d" in /usr/local/bin|"") continue ;; esac
  if [ -x "\$d/gh" ]; then real="\$d/gh"; break; fi
done
IFS=\$oldifs
if [ -z "\$real" ]; then
  echo "gh is not installed in this sandbox image" >&2
  exit 127
fi

# Caller-provided auth wins. The wrapper still observes successful PR creation.
caller_auth=
if [ -n "\${GH_TOKEN:-}" ] || [ -n "\${GITHUB_TOKEN:-}" ] || [ -f "\${GH_CONFIG_DIR:-\$HOME/.config/gh}/hosts.yml" ]; then caller_auth=1; fi

${SANDBOX_TOKEN_READ_SH}
token=
if [ -z "\$caller_auth" ] && [ -n "\$tok" ]; then
  remote=\$(git config --get remote.origin.url 2>/dev/null)
  owner=\$(printf '%s' "\$remote" | sed -n 's#.*[/:]\\([^/]*\\)/[^/]*\$#\\1#p')
  repo=\$(printf '%s' "\$remote" | sed -n 's#.*/\\([^/]*\\)\$#\\1#p')
  repo=\${repo%.git}
  resp=\$(curl --max-time 10 -fsS \\
    -X POST "${url}" \\
    -H "x-valet-sandbox: \$tok" \\
    -H "Content-Type: application/json" \\
    -d "{\\"host\\":\\"github.com\\",\\"owner\\":\\"\$owner\\",\\"repo\\":\\"\$repo\\",\\"purpose\\":\\"api\\"}" 2>/dev/null) || resp=
  token=\$(printf '%s' "\$resp" | sed -n 's/.*"password"[[:space:]]*:[[:space:]]*"\\([^"]*\\)".*/\\1/p')
fi

if [ "\${1:-}" = "pr" ] && [ "\${2:-}" = "create" ]; then
  if [ -n "\$token" ]; then output=\$(env GH_TOKEN="\$token" "\$real" "\$@" 2>&1); else output=\$("\$real" "\$@" 2>&1); fi
  status=\$?; printf '%s\\n' "\$output"; [ \$status -eq 0 ] || exit \$status
  url=\$(printf '%s\\n' "\$output" | sed -n 's#.*\\(https://github.com/[^ ]*/pull/[0-9][0-9]*\\).*#\\1#p' | tail -1)
  if [ -n "\$url" ] && [ -n "\$tok" ]; then
    remote=\$(git config --get remote.origin.url 2>/dev/null); owner=\$(printf '%s' "\$remote" | sed -n 's#.*[/:]\\([^/]*\\)/[^/]*\$#\\1#p'); repo=\$(printf '%s' "\$remote" | sed -n 's#.*/\\([^/]*\\)\$#\\1#p'); repo=\${repo%.git}
    head=\$(git rev-parse --abbrev-ref HEAD 2>/dev/null); sha=\$(git rev-parse HEAD 2>/dev/null); number=\${url##*/}
    curl --max-time 10 -fsS -X POST "${apiUrl.replace(/\/$/u, "")}/api/sandbox/git-pr/observe" -H "x-valet-sandbox: \$tok" -H "Content-Type: application/json" -d "{\\\"repoFullName\\\":\\\"\$owner/\$repo\\\",\\\"prNumber\\\":\$number,\\\"prUrl\\\":\\\"\$url\\\",\\\"headRef\\\":\\\"\$head\\\",\\\"headSha\\\":\\\"\$sha\\\"}" >/dev/null 2>&1 || true
  fi
  exit 0
fi
if [ -n "\$token" ]; then exec env GH_TOKEN="\$token" "\$real" "\$@"; fi
exec "\$real" "\$@"
`;
}

/** Transparent git shim for App-signed mode. Non-push commands chain to the image's git. */
export function appSignedGitWrapperScript(apiUrl: string): string {
  return String.raw`#!/usr/bin/env node
// Valet Git wrapper. Workspace prep preserves the image Git before install.
const { execFileSync, spawnSync } = require("node:child_process");
const fs = require("node:fs");
const real = "__REAL_GIT__";
const args = process.argv.slice(2);
function argsWithManagedHooks(gitArgs) {
  if (gitArgs[0] !== "commit") return { args: gitArgs, env: process.env };
  const gitDirResult = spawnSync(real, ["rev-parse", "--absolute-git-dir"], { encoding: "utf8" });
  if (gitDirResult.status !== 0) return { args: gitArgs, env: process.env };
  const gitDir = gitDirResult.stdout.trim(); const managedDir = gitDir + "/valet-hooks";
  if (!fs.existsSync(managedDir + "/valet-prepare-commit-msg")) return { args: gitArgs, env: process.env };
  if (process.env.VALET_HOOK_DISPATCH_ACTIVE === "1") {
    const original = process.env.VALET_REPO_HOOKS_DIR;
    return original ? { args: ["-c", "core.hooksPath=" + original, ...gitArgs], env: process.env } : { args: gitArgs, env: process.env };
  }
  const top = execFileSync(real, ["rev-parse", "--show-toplevel"], { encoding: "utf8" }).trim();
  const configured = spawnSync(real, ["config", "--path", "--get", "core.hooksPath"], { encoding: "utf8" });
  const configuredDir = configured.status === 0 ? configured.stdout.trim() : gitDir + "/hooks";
  const path = require("node:path");
  const original = path.isAbsolute(configuredDir) ? configuredDir : path.resolve(top, configuredDir);
  if (original === managedDir) return { args: gitArgs, env: process.env };
  return { args: ["-c", "core.hooksPath=" + managedDir, ...gitArgs], env: { ...process.env, VALET_REPO_HOOKS_DIR: original } };
}
if (args[0] !== "push") { const call = argsWithManagedHooks(args); process.exit(spawnSync(real, call.args, { stdio: "inherit", env: call.env }).status ?? 1); }
let releaseOwnedLock = () => {};
function fail(message) { releaseOwnedLock(); console.error("git push (Valet App signing): " + message); process.exit(2); }
const rest = args.slice(1); const upstream = rest.includes("-u") || rest.includes("--set-upstream");
if (rest.some((arg) => arg.startsWith("-") && arg !== "-u" && arg !== "--set-upstream")) fail("force, delete, tags, mirror, atomic, and custom push options are not supported in V1.");
const positional = rest.filter((arg) => arg !== "-u" && arg !== "--set-upstream");
if (positional.length > 2) fail("push exactly one branch at a time in V1.");
const remote = positional[0] || "origin"; const spec = positional[1] || "HEAD";
if (spec.startsWith(":") || spec.endsWith(":")) fail("branch deletion and empty refspec sides are not supported in V1.");
if (spec.includes("*") || spec.startsWith("+") || spec.includes("^")) fail("wildcard, forced, and exclusion refspecs are not supported in V1.");
const pieces = spec.split(":"); if (pieces.length > 2) fail("use one standard source:destination refspec.");
const src = pieces[0] || "HEAD";
const sourceRef = src === "HEAD"
  ? execFileSync(real, ["symbolic-ref", "HEAD"], { encoding: "utf8" }).trim()
  : execFileSync(real, ["rev-parse", "--symbolic-full-name", src], { encoding: "utf8" }).trim();
if (!sourceRef.startsWith("refs/heads/")) fail("the source must resolve to a local branch in V1.");
const localSha = execFileSync(real, ["rev-parse", "--verify", sourceRef + "^{commit}"], { encoding: "utf8" }).trim();
let destination = pieces[1];
if (!destination) destination = sourceRef.slice("refs/heads/".length);
if (destination.startsWith("refs/tags/") || (!destination.startsWith("refs/heads/") && destination.startsWith("refs/"))) fail("only branch destinations are supported in V1.");
const branch = destination.replace(/^refs\/heads\//, "");
if (!branch || branch === "HEAD" || branch.includes("..") || branch.startsWith("/") || branch.endsWith("/")) fail("the destination branch is invalid.");
const targetRef = "refs/heads/" + branch;
const remoteUrl = execFileSync(real, ["remote", "get-url", remote], { encoding: "utf8" }).trim();
const match = remoteUrl.match(/github\.com[/:]([^/]+)\/([^/]+?)(?:\.git)?$/i);
if (!match) fail("App-signed replay supports GitHub remotes only.");
const repoFullName = match[1] + "/" + match[2];
const ls = execFileSync(real, ["ls-remote", remote, targetRef], { encoding: "utf8" }).trim();
const createRef = !ls;
if (execFileSync(real, ["rev-parse", "--is-shallow-repository"], { encoding: "utf8" }).trim() === "true") fail("agent-created shallow clones cannot be App-signed. Fetch the complete parent history first.");
const expectedRemoteSha = createRef ? localSha : ls.split(/\s+/)[0];
const remoteRef = "refs/valet/remote/" + branch;
if (!createRef) execFileSync(real, ["fetch", "--quiet", remote, targetRef + ":" + remoteRef]);
const range = createRef ? [localSha, "--not", "--remotes=" + remote] : [localSha, "^" + remoteRef];
const commitIds = execFileSync(real, ["rev-list", "--reverse", ...range], { encoding: "utf8" }).trim().split("\n").filter(Boolean);
if (!commitIds.length) { console.log("Everything up-to-date"); process.exit(0); }
const commits = commitIds.map((sha) => { const raw = execFileSync(real, ["cat-file", "commit", sha]); const split = raw.indexOf(Buffer.from("\n\n")); const headers = raw.subarray(0, split).toString("utf8").split("\n"); const parents = headers.filter((line) => line.startsWith("parent ")).map((line) => line.slice(7)); for (const parent of parents) if (spawnSync(real, ["cat-file", "-e", parent + "^{commit}"]).status !== 0) fail("commit " + sha + " has missing parent " + parent + "; fetch the complete parent history before App signing."); return { localSha: sha, treeSha: headers.find((line) => line.startsWith("tree ")).slice(5), parents, message: raw.subarray(split + 2).toString("utf8") }; });
const objectLines = execFileSync(real, ["rev-list", "--objects", ...range], { encoding: "utf8" }).trim().split("\n").filter(Boolean);
const ids = [...new Set(objectLines.map((line) => line.split(" ")[0]))]; const blobs = []; const trees = []; const lfsObjects = []; const gitDir = execFileSync(real, ["rev-parse", "--absolute-git-dir"], { encoding: "utf8" }).trim();
const MAX_BLOB_BYTES = 100 * 1024 * 1024; const paths = new Map(objectLines.map((line) => { const space = line.indexOf(" "); return [line.slice(0, space < 0 ? line.length : space), space < 0 ? "(unknown path)" : line.slice(space + 1)]; }));
for (const sha of ids) { const type = execFileSync(real, ["cat-file", "-t", sha], { encoding: "utf8" }).trim(); if (type === "blob") { const size = Number(execFileSync(real, ["cat-file", "-s", sha], { encoding: "utf8" }).trim()); if (!Number.isSafeInteger(size) || size > MAX_BLOB_BYTES) fail("tracked blob " + paths.get(sha) + " is " + size + " bytes; GitHub Git Database accepts at most " + MAX_BLOB_BYTES + " bytes."); const content = execFileSync(real, ["cat-file", "blob", sha], { maxBuffer: MAX_BLOB_BYTES + 1 }); blobs.push({ sha, contentBase64: content.toString("base64") }); const pointer = content.toString("utf8").match(/^version https:\/\/git-lfs.github.com\/spec\/v1\noid sha256:([0-9a-f]{64})\nsize ([0-9]+)\n?$/); if (pointer) { const file = gitDir + "/lfs/objects/" + pointer[1].slice(0, 2) + "/" + pointer[1].slice(2, 4) + "/" + pointer[1]; if (!fs.existsSync(file)) fail("LFS object " + pointer[1] + " is missing locally."); lfsObjects.push({ oid: pointer[1], size: Number(pointer[2]), contentBase64: fs.readFileSync(file).toString("base64") }); } } if (type === "tree") { const raw = execFileSync(real, ["ls-tree", "-z", sha]); const entries = raw.toString("utf8").split("\0").filter(Boolean).map((line) => { const tab = line.indexOf("\t"); const [mode, entryType, entrySha] = line.slice(0, tab).split(" "); return { path: line.slice(tab + 1), mode, type: entryType, sha: entrySha }; }); trees.push({ sha, entries }); } }
const tok = (() => { try { return fs.readFileSync("/etc/valet/creds/token", "utf8").trim(); } catch { return process.env.VALET_SANDBOX_TOKEN || ""; } })();
if (!tok) fail("the sandbox credential is unavailable; restart the session.");
(async () => {
const lockPath = gitDir + "/valet-reconcile.lock"; const lockToken = process.pid + "-" + Date.now() + "-" + Math.random().toString(16).slice(2); let ownsLock = false;
function lockOwner() { try { return JSON.parse(fs.readFileSync(lockPath, "utf8")); } catch { return null; } }
function ownerIsLive(owner) { if (!owner || !Number.isInteger(owner.pid) || owner.pid <= 0) return false; try { process.kill(owner.pid, 0); return true; } catch (error) { return error && error.code === "EPERM"; } }
function releaseLock() { if (!ownsLock) return; const owner = lockOwner(); if (owner && owner.token === lockToken) { try { fs.unlinkSync(lockPath); } catch {} } ownsLock = false; }
releaseOwnedLock = releaseLock;
function acquireLock() {
  const metadata = JSON.stringify({ pid: process.pid, createdAt: Date.now(), token: lockToken });
  for (let attempt = 0; attempt < 2; attempt++) {
    try { const fd = fs.openSync(lockPath, "wx"); try { fs.writeFileSync(fd, metadata); } finally { fs.closeSync(fd); } ownsLock = true; return; }
    catch (error) {
      if (!error || error.code !== "EEXIST") throw error;
      const owner = lockOwner(); const age = Date.now() - fs.statSync(lockPath).mtimeMs;
      if (ownerIsLive(owner)) fail("reconcile lock " + lockPath + " is held by live process " + owner.pid + ". Wait for that push to finish. If the process exits without cleanup, remove " + lockPath + " and retry.");
      if (!owner && age < 15 * 60 * 1000) fail("reconcile lock " + lockPath + " has invalid recent metadata. Wait 15 minutes, or verify that no signed push is active, remove " + lockPath + ", and retry.");
      try { fs.unlinkSync(lockPath); } catch (unlinkError) { if (!unlinkError || unlinkError.code !== "ENOENT") throw unlinkError; }
    }
  }
  fail("could not acquire reconcile lock " + lockPath + ". Verify that no signed push is active, remove the stale lock, and retry.");
}
acquireLock();
try {
const startHead = execFileSync(real, ["rev-parse", "HEAD"], { encoding: "utf8" }).trim(); const startSource = execFileSync(real, ["rev-parse", sourceRef], { encoding: "utf8" }).trim(); const checkedOutSource = spawnSync(real, ["symbolic-ref", "--quiet", "HEAD"], { encoding: "utf8" }).stdout.trim() === sourceRef; const startStatus = execFileSync(real, ["status", "--porcelain=v1", "-z"]); const startIndex = execFileSync(real, ["write-tree"], { encoding: "utf8" }).trim();
const response = await fetch("__API__/api/sandbox/git-push", { method: "POST", headers: { "content-type": "application/json", "x-valet-sandbox": tok }, body: JSON.stringify({ repoFullName, targetRef, expectedRemoteSha, createRef, blobs, trees, lfsObjects, commits }) }); const body = await response.json(); if (!response.ok) fail(body.error || "host replay failed");
if (execFileSync(real, ["rev-parse", sourceRef], { encoding: "utf8" }).trim() !== startSource) fail("the pushed source branch changed during replay; the signed ref is published. Retry to reconcile it.");
if (checkedOutSource && (execFileSync(real, ["rev-parse", "HEAD"], { encoding: "utf8" }).trim() !== startHead || !execFileSync(real, ["status", "--porcelain=v1", "-z"]).equals(startStatus) || execFileSync(real, ["write-tree"], { encoding: "utf8" }).trim() !== startIndex)) fail("local HEAD, index, or working tree changed during replay; the signed ref is published. Retry to reconcile it.");
const signedRef = "refs/valet/signed/" + branch; execFileSync(real, ["fetch", "--quiet", remote, targetRef + ":" + signedRef]);
if (execFileSync(real, ["rev-parse", signedRef], { encoding: "utf8" }).trim() !== body.signedHeadSha) fail("the published signed head changed before local reconciliation.");
const localTree = execFileSync(real, ["rev-parse", startSource + "^{tree}"], { encoding: "utf8" }).trim(); const signedTree = execFileSync(real, ["rev-parse", body.signedHeadSha + "^{tree}"], { encoding: "utf8" }).trim(); if (localTree !== signedTree) fail("the signed commit tree differs from the pushed source branch; local history was not changed.");
execFileSync(real, ["update-ref", "refs/valet/backup/" + sourceRef.slice("refs/heads/".length), startSource]); execFileSync(real, ["update-ref", sourceRef, body.signedHeadSha, startSource]); execFileSync(real, ["update-ref", "refs/remotes/" + remote + "/" + branch, body.signedHeadSha]);
const reconciled = await fetch("__API__/api/sandbox/git-push/" + encodeURIComponent(body.operationId) + "/reconcile", { method: "POST", headers: { "content-type": "application/json", "x-valet-sandbox": tok } }); if (!reconciled.ok) fail("the signed push was published locally, but operation reconciliation failed. Retry the push.");
if (upstream) spawnSync(real, ["branch", "--set-upstream-to", remote + "/" + branch, sourceRef], { stdio: "ignore" }); console.log("To " + remoteUrl + "\n   " + expectedRemoteSha.slice(0, 7) + ".." + body.signedHeadSha.slice(0, 7) + "  " + sourceRef.slice("refs/heads/".length) + " -> " + branch);
} finally { releaseLock(); }
})().catch((error) => fail(error.message));
`.replace("__REAL_GIT__", REAL_GIT_PATH).replaceAll("__API__", apiUrl.replace(/\/$/u, ""));
}

/** Git shim for unsigned modes. It records a successful ordinary branch push. */
export function observedGitWrapperScript(apiUrl: string): string {
  return `#!/bin/sh
# Valet Git wrapper. Run the preserved image Git. The managed dispatcher keeps working if a
# repository changes core.hooksPath after workspace prep.
real=${REAL_GIT_PATH}
if [ "\${1:-}" = commit ]; then
  git_dir=$("$real" rev-parse --absolute-git-dir 2>/dev/null) || git_dir=
  managed="$git_dir/valet-hooks"
  if [ -n "$git_dir" ] && [ -x "$managed/valet-prepare-commit-msg" ]; then
    if [ "\${VALET_HOOK_DISPATCH_ACTIVE:-}" = 1 ]; then
      [ -n "\${VALET_REPO_HOOKS_DIR:-}" ] && exec "$real" -c core.hooksPath="$VALET_REPO_HOOKS_DIR" "$@"
    else
      configured=$("$real" config --path --get core.hooksPath 2>/dev/null) || configured="$git_dir/hooks"
      case "$configured" in /*) original="$configured" ;; *) top=$("$real" rev-parse --show-toplevel); original="$top/$configured" ;; esac
      [ "$original" = "$managed" ] || { VALET_REPO_HOOKS_DIR="$original" "$real" -c core.hooksPath="$managed" "$@"; exit $?; }
    fi
  fi
fi
# Observation must never change the push result.
"$real" "$@"
status=$?
[ $status -eq 0 ] || exit $status
[ "\${1:-}" = "push" ] || exit 0
shift

# V1 observes one ordinary branch refspec. Unsupported forms still push, but
# they do not create an attribution record.
remote=origin
spec=HEAD
while [ $# -gt 0 ]; do
  case "$1" in
    -u|--set-upstream) shift ;;
    -*) exit 0 ;;
    *) remote=$1; shift; [ $# -eq 0 ] || { spec=$1; shift; }; break ;;
  esac
done
[ $# -eq 0 ] || exit 0
case "$spec" in :*|*:|*\\**|+*|*^*) exit 0 ;; esac
case "$spec" in
  *:*) src=\${spec%%:*}; dst=\${spec#*:} ;;
  *) src=$spec; dst= ;;
esac
[ -n "$src" ] || src=HEAD
if [ -z "$dst" ]; then
  if [ "$src" = HEAD ]; then dst=$("$real" symbolic-ref --short HEAD 2>/dev/null) || exit 0
  else dst=\${src#refs/heads/}
  fi
fi
case "$dst" in refs/tags/*|refs/*) case "$dst" in refs/heads/*) ;; *) exit 0 ;; esac ;; esac
case "$dst" in refs/heads/*) target_ref=$dst ;; *) target_ref=refs/heads/$dst ;; esac
head_sha=$("$real" rev-parse --verify "$src^{commit}" 2>/dev/null) || exit 0
url=$("$real" remote get-url "$remote" 2>/dev/null) || exit 0
repo=$(printf '%s' "$url" | sed -n 's#.*github\\.com[/:]\\([^/]*\\)/\\([^/]*\\)\\(.git\\)\\?$#\\1/\\2#p')
repo=\${repo%.git}
[ -n "$repo" ] || exit 0
${SANDBOX_TOKEN_READ_SH}
[ -n "$tok" ] || exit 0
curl --max-time 10 -fsS -X POST "${apiUrl.replace(/\/$/u, "")}/api/sandbox/git-push/observe" \\
  -H "x-valet-sandbox: $tok" -H "Content-Type: application/json" \\
  -d "{\\"repoFullName\\":\\"$repo\\",\\"targetRef\\":\\"$target_ref\\",\\"headSha\\":\\"$head_sha\\"}" >/dev/null 2>&1 || true
exit 0
`;
}
