/**
 * Golden tests for the in-sandbox git credential script generators
 * (GitHub/repo integration plan, Task 8). These pin the exact script text
 * so a shape change is a visible diff, and enforce the security invariant
 * that NO token material is ever embedded — only `$VALET_SANDBOX_TOKEN`
 * references and the (non-secret) API URL.
 */
import { describe, expect, it } from "vitest";
import { gitCredentialHelperScript, ghWrapperScript } from "./git-credential-helper.js";

const API_URL = "http://valet-api.example.com";

describe("gitCredentialHelperScript", () => {
  it("matches the golden", () => {
    expect(gitCredentialHelperScript(API_URL)).toBe(`#!/bin/sh
# git-credential-valet — resolves a per-owner git token from the Valet API.
# Generated by @valet/api (engine/git-credential-helper.ts); installed by
# sandbox prep. Only the 'get' verb does work; 'store'/'erase' are no-ops.
# No token material is embedded here: the sandbox token is read from
# $VALET_SANDBOX_TOKEN at call time.
set -eu

[ "\${1:-}" = "get" ] || exit 0

host=
path=
while IFS='=' read -r key value; do
  case "$key" in
    host) host=$value ;;
    path) path=$value ;;
  esac
done

owner=\${path%%/*}
repo=
case "$path" in
  */*) repo=\${path#*/}; repo=\${repo%%/*}; repo=\${repo%.git} ;;
esac
[ -n "$owner" ] || exit 0
[ -n "\${VALET_SANDBOX_TOKEN:-}" ] || exit 0

resp=$(curl --max-time 10 -fsS \\
  -X POST "http://valet-api.example.com/api/sandbox/git-credential" \\
  -H "x-valet-sandbox: $VALET_SANDBOX_TOKEN" \\
  -H "Content-Type: application/json" \\
  -d "{\\"host\\":\\"$host\\",\\"owner\\":\\"$owner\\",\\"repo\\":\\"$repo\\"}") || exit 0

username=$(printf '%s' "$resp" | sed -n 's/.*"username"[[:space:]]*:[[:space:]]*"\\([^"]*\\)".*/\\1/p')
password=$(printf '%s' "$resp" | sed -n 's/.*"password"[[:space:]]*:[[:space:]]*"\\([^"]*\\)".*/\\1/p')

[ -n "$username" ] || exit 0
[ -n "$password" ] || exit 0

printf 'username=%s\\n' "$username"
printf 'password=%s\\n' "$password"
`);
  });

  it("uses the x-valet-sandbox header, not Authorization: Bearer", () => {
    const script = gitCredentialHelperScript(API_URL);
    expect(script).toContain("x-valet-sandbox: $VALET_SANDBOX_TOKEN");
    expect(script).not.toContain("Authorization");
  });

  it("embeds only the API URL as an env-referenced $VALET_SANDBOX_TOKEN — never a literal token", () => {
    const script = gitCredentialHelperScript(API_URL);
    // The only place the token appears is as a shell variable reference.
    expect(script).toContain("$VALET_SANDBOX_TOKEN");
    // No literal sandbox token material (`st_` prefix) or GitHub token
    // prefixes should ever be baked in.
    expect(script).not.toMatch(/st_[0-9a-f]/);
    expect(script).not.toMatch(/gh[pousr]_/);
  });

  it("no-ops non-get verbs and derives owner from the path's first segment", () => {
    const script = gitCredentialHelperScript(API_URL);
    expect(script).toContain('[ "${1:-}" = "get" ] || exit 0');
    expect(script).toContain("owner=${path%%/*}");
  });
});

describe("ghWrapperScript", () => {
  it("matches the golden", () => {
    expect(ghWrapperScript(API_URL)).toBe(`#!/bin/sh
# valet-gh — runs 'gh' with a Valet-resolved GH_TOKEN for the current repo's
# owner when one is available, else plain 'gh'. Generated by @valet/api
# (engine/git-credential-helper.ts); installed by sandbox prep. No token
# material is embedded: the sandbox token is read from $VALET_SANDBOX_TOKEN.
set -u

token=
remote=$(git config --get remote.origin.url 2>/dev/null)
owner=$(printf '%s' "$remote" | sed -n 's#.*[/:]\\([^/]*\\)/[^/]*$#\\1#p')
repo=$(printf '%s' "$remote" | sed -n 's#.*/\\([^/]*\\)$#\\1#p')
repo=\${repo%.git}

if [ -n "$owner" ] && [ -n "\${VALET_SANDBOX_TOKEN:-}" ]; then
  resp=$(curl --max-time 10 -fsS \\
    -X POST "http://valet-api.example.com/api/sandbox/git-credential" \\
    -H "x-valet-sandbox: $VALET_SANDBOX_TOKEN" \\
    -H "Content-Type: application/json" \\
    -d "{\\"host\\":\\"github.com\\",\\"owner\\":\\"$owner\\",\\"repo\\":\\"$repo\\"}" 2>/dev/null) || resp=
  token=$(printf '%s' "$resp" | sed -n 's/.*"password"[[:space:]]*:[[:space:]]*"\\([^"]*\\)".*/\\1/p')
fi

if [ -n "$token" ]; then
  exec env GH_TOKEN="$token" gh "$@"
fi
exec gh "$@"
`);
  });

  it("execs gh plainly when no token resolves, with token via env only", () => {
    const script = ghWrapperScript(API_URL);
    expect(script).toContain('exec gh "$@"');
    expect(script).toContain('exec env GH_TOKEN="$token" gh "$@"');
  });

  it("never embeds token material", () => {
    const script = ghWrapperScript(API_URL);
    expect(script).toContain("$VALET_SANDBOX_TOKEN");
    expect(script).not.toMatch(/st_[0-9a-f]/);
    expect(script).not.toMatch(/gh[pousr]_/);
  });
});
