/**
 * In-sandbox git credential surface — pure script-text generators
 * (GitHub/repo integration plan, Task 8). These produce POSIX `sh` scripts
 * that sandbox prep (Task 9) writes to disk and wires into git / `gh`. They
 * are unit-tested against goldens; keep them deterministic (no timestamps,
 * no randomness) so the goldens stay stable.
 *
 * ── Security invariants (pinned by the golden tests) ─────────────────────
 *   - NO token material is ever embedded in the generated text. The sandbox
 *     token is read from the `$VALET_SANDBOX_TOKEN` environment variable at
 *     call time (every sandbox already has it — see
 *     `engine/host.ts`'s `mintSandboxEnv`). The only interpolated value is
 *     `apiUrl`, which is not secret.
 *   - The scripts authenticate to the API with the `x-valet-sandbox` header
 *     — the same header `middleware/auth.ts`'s sandbox rung verifies. (The
 *     task brief floated `Authorization: Bearer`, but the middleware only
 *     reads `x-valet-sandbox`; the middleware is ground truth.)
 *
 * ── Why `#!/bin/sh` and not bash ─────────────────────────────────────────
 * The sandbox images ship bash, but nothing here needs a bashism, so the
 * scripts target plain POSIX `sh` for portability. Response parsing uses
 * `sed` (GitHub tokens and the `x-access-token` username contain no `"` or
 * `\`, so a `"\([^"]*\)"` capture is safe) rather than assuming `jq`.
 */

/** Path (relative to the API base) of the credential-minting route. */
const ROUTE_PATH = "/api/sandbox/git-credential";

/**
 * `git-credential-valet` — a git credential helper (see `gitcredentials(7)`).
 *
 * git invokes it as `helper <verb>` and pipes the request attributes
 * (`protocol=`, `host=`, and — ONLY when `credential.useHttpPath` is true —
 * `path=`) on stdin, one `key=value` per line, terminated by a blank line.
 * HARD PREREQUISITE: git does NOT send `path=` by default, and this helper
 * derives `owner` from it — workspace prep MUST run
 * `git config --global credential.useHttpPath true` in the sandbox or the
 * helper exits silently and every clone runs anonymous. Only the `get` verb
 * does work; `store` and `erase` are no-ops (exit 0). On `get` we:
 *   1. parse `host` and `path` from stdin,
 *   2. derive `owner` as the first path segment (`owner/repo.git` → `owner`),
 *   3. POST `{host, owner}` to the credential route with the sandbox token,
 *   4. emit `username=`/`password=` lines when the API returns a credential,
 *      or nothing (letting git proceed unauthenticated) on `{anonymous:true}`,
 *      an HTTP error (403 unbound / 409 credential-unavailable), a network
 *      failure, or a missing token.
 */
export function gitCredentialHelperScript(apiUrl: string): string {
  const url = `${apiUrl}${ROUTE_PATH}`;
  return `#!/bin/sh
# git-credential-valet — resolves a per-owner git token from the Valet API.
# Generated by @valet/api (engine/git-credential-helper.ts); installed by
# sandbox prep. Only the 'get' verb does work; 'store'/'erase' are no-ops.
# No token material is embedded here: the sandbox token is read from
# \$VALET_SANDBOX_TOKEN at call time.
set -eu

[ "\${1:-}" = "get" ] || exit 0

host=
path=
while IFS='=' read -r key value; do
  case "\$key" in
    host) host=\$value ;;
    path) path=\$value ;;
  esac
done

owner=\${path%%/*}
[ -n "\$owner" ] || exit 0
[ -n "\${VALET_SANDBOX_TOKEN:-}" ] || exit 0

resp=\$(curl --max-time 10 -fsS \\
  -X POST "${url}" \\
  -H "x-valet-sandbox: \$VALET_SANDBOX_TOKEN" \\
  -H "Content-Type: application/json" \\
  -d "{\\"host\\":\\"\$host\\",\\"owner\\":\\"\$owner\\"}") || exit 0

username=\$(printf '%s' "\$resp" | sed -n 's/.*"username"[[:space:]]*:[[:space:]]*"\\([^"]*\\)".*/\\1/p')
password=\$(printf '%s' "\$resp" | sed -n 's/.*"password"[[:space:]]*:[[:space:]]*"\\([^"]*\\)".*/\\1/p')

[ -n "\$username" ] || exit 0
[ -n "\$password" ] || exit 0

printf 'username=%s\\n' "\$username"
printf 'password=%s\\n' "\$password"
`;
}

/**
 * `valet-gh` — a thin `gh` wrapper that injects a Valet-resolved `GH_TOKEN`
 * for the current repository's owner when one is available, then execs the
 * real `gh` with the caller's arguments unchanged.
 *
 * The owner is derived from the current repo's `origin` remote (git config),
 * NOT from a "first bound owner" API lookup — there is no owner-listing
 * endpoint, and deriving from the remote is both simpler and more correct
 * (the token matches the repo `gh` is actually operating on). When there is
 * no repo/remote (`gh` used repo-independently, e.g. `gh api /user`), or no
 * credential is available, it execs `gh` plainly — the token fetch is
 * strictly best-effort and never blocks the command. No token material is
 * embedded; the sandbox token is read from `$VALET_SANDBOX_TOKEN`.
 */
export function ghWrapperScript(apiUrl: string): string {
  const url = `${apiUrl}${ROUTE_PATH}`;
  return `#!/bin/sh
# valet-gh — runs 'gh' with a Valet-resolved GH_TOKEN for the current repo's
# owner when one is available, else plain 'gh'. Generated by @valet/api
# (engine/git-credential-helper.ts); installed by sandbox prep. No token
# material is embedded: the sandbox token is read from \$VALET_SANDBOX_TOKEN.
set -u

token=
owner=\$(git config --get remote.origin.url 2>/dev/null \\
  | sed -n 's#.*[/:]\\([^/]*\\)/[^/]*\$#\\1#p')

if [ -n "\$owner" ] && [ -n "\${VALET_SANDBOX_TOKEN:-}" ]; then
  resp=\$(curl --max-time 10 -fsS \\
    -X POST "${url}" \\
    -H "x-valet-sandbox: \$VALET_SANDBOX_TOKEN" \\
    -H "Content-Type: application/json" \\
    -d "{\\"host\\":\\"github.com\\",\\"owner\\":\\"\$owner\\"}" 2>/dev/null) || resp=
  token=\$(printf '%s' "\$resp" | sed -n 's/.*"password"[[:space:]]*:[[:space:]]*"\\([^"]*\\)".*/\\1/p')
fi

if [ -n "\$token" ]; then
  exec env GH_TOKEN="\$token" gh "\$@"
fi
exec gh "\$@"
`;
}
