/**
 * Golden tests for the in-sandbox git credential script generators
 * (GitHub/repo integration plan, Task 8). These pin the exact script text
 * so a shape change is a visible diff, and enforce the security invariant
 * that NO token material is ever embedded — the sandbox token is read from
 * `/etc/valet/creds/token` (the creds mount) first, then from the
 * `$VALET_SANDBOX_TOKEN` environment variable as a fallback. The only
 * interpolated value is `apiUrl`, which is not secret.
 */
import { describe, expect, it } from "vitest";
import { gitCredentialHelperScript, ghWrapperScript } from "./git-credential-helper.js";

const API_URL = "http://valet-api.example.com";

describe("gitCredentialHelperScript", () => {
  it("matches the golden", () => {
    expect(gitCredentialHelperScript(API_URL)).toBe(`#!/bin/sh
# git-credential-valet — resolves a per-owner git token from the Valet API.
# Generated by @valet/api (engine/git-credential-helper.ts); installed by
# sandbox prep. Only the 'get' verb does work; 'store'/'erase' are no-ops.
# No token material is embedded here: the sandbox token is read from the
# creds mount (/etc/valet/creds/token) first, then $VALET_SANDBOX_TOKEN.
set -eu

[ "\${1:-}" = "get" ] || exit 0

host=
path=
while IFS='=' read -r key value; do
  case "$key" in
    host) host=$value ;;
    path) path=$value ;;
  esac
done

owner=\${path%%/*}
repo=
case "$path" in
  */*) repo=\${path#*/}; repo=\${repo%%/*}; repo=\${repo%.git} ;;
esac
[ -n "$owner" ] || exit 0
tok=$(cat /etc/valet/creds/token 2>/dev/null)
[ -n "$tok" ] || tok=\${VALET_SANDBOX_TOKEN:-}
[ -n "$tok" ] || exit 0

resp=$(curl --max-time 10 -fsS \\
  -X POST "http://valet-api.example.com/api/sandbox/git-credential" \\
  -H "x-valet-sandbox: $tok" \\
  -H "Content-Type: application/json" \\
  -d "{\\"host\\":\\"$host\\",\\"owner\\":\\"$owner\\",\\"repo\\":\\"$repo\\"}") || exit 0

username=$(printf '%s' "$resp" | sed -n 's/.*"username"[[:space:]]*:[[:space:]]*"\\([^"]*\\)".*/\\1/p')
password=$(printf '%s' "$resp" | sed -n 's/.*"password"[[:space:]]*:[[:space:]]*"\\([^"]*\\)".*/\\1/p')

[ -n "$username" ] || exit 0
[ -n "$password" ] || exit 0

printf 'username=%s\\n' "$username"
printf 'password=%s\\n' "$password"
`);
  });

  it("uses the x-valet-sandbox header, not Authorization: Bearer", () => {
    const script = gitCredentialHelperScript(API_URL);
    expect(script).toContain("x-valet-sandbox: $tok");
    expect(script).not.toContain("Authorization");
  });

  it("reads the creds mount before falling back to the env variable", () => {
    const script = gitCredentialHelperScript(API_URL);
    // Creds mount read must precede the env fallback assignment.
    const credsReadAt = script.indexOf("cat /etc/valet/creds/token");
    const envFallbackAt = script.indexOf("VALET_SANDBOX_TOKEN:-}");
    expect(credsReadAt).toBeGreaterThan(-1);
    expect(envFallbackAt).toBeGreaterThan(-1);
    expect(credsReadAt).toBeLessThan(envFallbackAt);
  });

  it("embeds only the API URL as non-secret — never literal token material", () => {
    const script = gitCredentialHelperScript(API_URL);
    // The creds mount path and env var name appear; no literal token values.
    expect(script).toContain("/etc/valet/creds/token");
    expect(script).toContain("VALET_SANDBOX_TOKEN");
    // No literal sandbox token material (`st_` prefix) or GitHub token
    // prefixes should ever be baked in.
    expect(script).not.toMatch(/st_[0-9a-f]/);
    expect(script).not.toMatch(/gh[pousr]_/);
  });

  it("no-ops non-get verbs and derives owner from the path's first segment", () => {
    const script = gitCredentialHelperScript(API_URL);
    expect(script).toContain('[ "${1:-}" = "get" ] || exit 0');
    expect(script).toContain("owner=${path%%/*}");
  });
});

describe("ghWrapperScript", () => {
  it("matches the golden", () => {
    expect(ghWrapperScript(API_URL)).toBe(`#!/bin/sh
# gh (Valet shim, also installed as valet-gh) — runs the real 'gh' with a
# Valet-resolved GH_TOKEN when you have not authenticated yourself; your own
# GH_TOKEN/GITHUB_TOKEN or 'gh auth login' always wins. Generated by
# @valet/api (engine/git-credential-helper.ts); installed by sandbox prep.
# No token material is embedded here: the sandbox token is read from the
# creds mount (/etc/valet/creds/token) first, then $VALET_SANDBOX_TOKEN.
set -u

# The real gh: first executable named 'gh' on PATH outside /usr/local/bin
# (this shim's fixed install dir — skipping it prevents self-exec).
real=
oldifs=$IFS
IFS=:
for d in $PATH; do
  case "$d" in /usr/local/bin|"") continue ;; esac
  if [ -x "$d/gh" ]; then real="$d/gh"; break; fi
done
IFS=$oldifs
if [ -z "$real" ]; then
  echo "gh is not installed in this sandbox image" >&2
  exit 127
fi

# Caller-provided auth wins: env token or a completed 'gh auth login'.
if [ -n "\${GH_TOKEN:-}" ] || [ -n "\${GITHUB_TOKEN:-}" ]; then exec "$real" "$@"; fi
if [ -f "\${GH_CONFIG_DIR:-$HOME/.config/gh}/hosts.yml" ]; then exec "$real" "$@"; fi

tok=$(cat /etc/valet/creds/token 2>/dev/null)
[ -n "$tok" ] || tok=\${VALET_SANDBOX_TOKEN:-}
token=
if [ -n "$tok" ]; then
  remote=$(git config --get remote.origin.url 2>/dev/null)
  owner=$(printf '%s' "$remote" | sed -n 's#.*[/:]\\([^/]*\\)/[^/]*$#\\1#p')
  repo=$(printf '%s' "$remote" | sed -n 's#.*/\\([^/]*\\)$#\\1#p')
  repo=\${repo%.git}
  resp=$(curl --max-time 10 -fsS \\
    -X POST "http://valet-api.example.com/api/sandbox/git-credential" \\
    -H "x-valet-sandbox: $tok" \\
    -H "Content-Type: application/json" \\
    -d "{\\"host\\":\\"github.com\\",\\"owner\\":\\"$owner\\",\\"repo\\":\\"$repo\\",\\"purpose\\":\\"api\\"}" 2>/dev/null) || resp=
  token=$(printf '%s' "$resp" | sed -n 's/.*"password"[[:space:]]*:[[:space:]]*"\\([^"]*\\)".*/\\1/p')
fi

if [ -n "$token" ]; then
  exec env GH_TOKEN="$token" "$real" "$@"
fi
exec "$real" "$@"
`);
  });

  it("execs the real gh (never itself) with token via env only", () => {
    const script = ghWrapperScript(API_URL);
    expect(script).toContain('exec "$real" "$@"');
    expect(script).toContain('exec env GH_TOKEN="$token" "$real" "$@"');
    // The shim installs at /usr/local/bin/gh; the PATH scan must skip that
    // dir or the shim would exec itself forever.
    expect(script).toContain('case "$d" in /usr/local/bin|"") continue ;; esac');
  });

  it("caller auth wins: env tokens and hosts.yml short-circuit before any fetch", () => {
    const script = ghWrapperScript(API_URL);
    const fetchAt = script.indexOf("curl");
    expect(script.indexOf("GH_TOKEN:-")).toBeLessThan(fetchAt);
    expect(script.indexOf("GITHUB_TOKEN:-")).toBeLessThan(fetchAt);
    expect(script.indexOf("hosts.yml")).toBeLessThan(fetchAt);
  });

  it("requests purpose=api so repo-independent gh calls hit the user-first ladder", () => {
    expect(ghWrapperScript(API_URL)).toContain('\\"purpose\\":\\"api\\"');
  });

  it("reads the creds mount before falling back to the env variable", () => {
    const script = ghWrapperScript(API_URL);
    // Creds mount read must precede the env fallback assignment.
    const credsReadAt = script.indexOf("cat /etc/valet/creds/token");
    const envFallbackAt = script.indexOf("VALET_SANDBOX_TOKEN:-}");
    expect(credsReadAt).toBeGreaterThan(-1);
    expect(envFallbackAt).toBeGreaterThan(-1);
    expect(credsReadAt).toBeLessThan(envFallbackAt);
  });

  it("never embeds token material", () => {
    const script = ghWrapperScript(API_URL);
    // The creds mount path and env var name appear; no literal token values.
    expect(script).toContain("/etc/valet/creds/token");
    expect(script).toContain("VALET_SANDBOX_TOKEN");
    expect(script).not.toMatch(/st_[0-9a-f]/);
    expect(script).not.toMatch(/gh[pousr]_/);
  });
});
