/**
 * In-sandbox git credential surface — pure script-text generators
 * (GitHub/repo integration plan, Task 8). These produce POSIX `sh` scripts
 * that sandbox prep (Task 9) writes to disk and wires into git / `gh`. They
 * are unit-tested against goldens; keep them deterministic (no timestamps,
 * no randomness) so the goldens stay stable.
 *
 * ── Security invariants (pinned by the golden tests) ─────────────────────
 *   - NO token material is ever embedded in the generated text. The sandbox
 *     token is read from the `$VALET_SANDBOX_TOKEN` environment variable at
 *     call time (every sandbox already has it — see
 *     `engine/host.ts`'s `mintSandboxEnv`). The only interpolated value is
 *     `apiUrl`, which is not secret.
 *   - The scripts authenticate to the API with the `x-valet-sandbox` header
 *     — the same header `middleware/auth.ts`'s sandbox rung verifies. (The
 *     task brief floated `Authorization: Bearer`, but the middleware only
 *     reads `x-valet-sandbox`; the middleware is ground truth.)
 *
 * ── Why `#!/bin/sh` and not bash ─────────────────────────────────────────
 * The sandbox images ship bash, but nothing here needs a bashism, so the
 * scripts target plain POSIX `sh` for portability. Response parsing uses
 * `sed` (GitHub tokens and the `x-access-token` username contain no `"` or
 * `\`, so a `"\([^"]*\)"` capture is safe) rather than assuming `jq`.
 */

/** Path (relative to the API base) of the credential-minting route. */
const ROUTE_PATH = "/api/sandbox/git-credential";

/**
 * `git-credential-valet` — a git credential helper (see `gitcredentials(7)`).
 *
 * git invokes it as `helper <verb>` and pipes the request attributes
 * (`protocol=`, `host=`, and — ONLY when `credential.useHttpPath` is true —
 * `path=`) on stdin, one `key=value` per line, terminated by a blank line.
 * HARD PREREQUISITE: git does NOT send `path=` by default, and this helper
 * derives `owner` from it — workspace prep MUST run
 * `git config --global credential.useHttpPath true` in the sandbox or the
 * helper exits silently and every clone runs anonymous. Only the `get` verb
 * does work; `store` and `erase` are no-ops (exit 0). On `get` we:
 *   1. parse `host` and `path` from stdin,
 *   2. derive `owner` as the first path segment (`owner/repo.git` → `owner`)
 *      and `repo` as the second (`.git` stripped; empty when git sent no repo
 *      segment) — `repo` lets the route pick the right binding when a session
 *      has two repos under one owner with different auth,
 *   3. POST `{host, owner, repo}` to the credential route with the sandbox token,
 *   4. emit `username=`/`password=` lines when the API returns a credential,
 *      or nothing (letting git proceed unauthenticated) on `{anonymous:true}`,
 *      an HTTP error (403 unbound / 409 credential-unavailable), a network
 *      failure, or a missing token.
 */
export function gitCredentialHelperScript(apiUrl: string): string {
  const url = `${apiUrl}${ROUTE_PATH}`;
  return `#!/bin/sh
# git-credential-valet — resolves a per-owner git token from the Valet API.
# Generated by @valet/api (engine/git-credential-helper.ts); installed by
# sandbox prep. Only the 'get' verb does work; 'store'/'erase' are no-ops.
# No token material is embedded here: the sandbox token is read from
# \$VALET_SANDBOX_TOKEN at call time.
set -eu

[ "\${1:-}" = "get" ] || exit 0

host=
path=
while IFS='=' read -r key value; do
  case "\$key" in
    host) host=\$value ;;
    path) path=\$value ;;
  esac
done

owner=\${path%%/*}
repo=
case "\$path" in
  */*) repo=\${path#*/}; repo=\${repo%%/*}; repo=\${repo%.git} ;;
esac
[ -n "\$owner" ] || exit 0
[ -n "\${VALET_SANDBOX_TOKEN:-}" ] || exit 0

resp=\$(curl --max-time 10 -fsS \\
  -X POST "${url}" \\
  -H "x-valet-sandbox: \$VALET_SANDBOX_TOKEN" \\
  -H "Content-Type: application/json" \\
  -d "{\\"host\\":\\"\$host\\",\\"owner\\":\\"\$owner\\",\\"repo\\":\\"\$repo\\"}") || exit 0

username=\$(printf '%s' "\$resp" | sed -n 's/.*"username"[[:space:]]*:[[:space:]]*"\\([^"]*\\)".*/\\1/p')
password=\$(printf '%s' "\$resp" | sed -n 's/.*"password"[[:space:]]*:[[:space:]]*"\\([^"]*\\)".*/\\1/p')

[ -n "\$username" ] || exit 0
[ -n "\$password" ] || exit 0

printf 'username=%s\\n' "\$username"
printf 'password=%s\\n' "\$password"
`;
}

/**
 * The `gh` PATH shim (also kept at its historical `valet-gh` name) — injects
 * a Valet-resolved `GH_TOKEN` when the caller has not brought auth of their
 * own, then execs the REAL `gh` with the arguments unchanged.
 *
 * Sandbox prep installs this at `/usr/local/bin/gh`, which shadows the
 * image's `/usr/bin/gh` on PATH — so a plain `gh pr list` transparently
 * authenticates without the agent knowing the shim exists. The real binary
 * is located by scanning PATH and skipping `/usr/local/bin` (the shim's own
 * fixed install dir), which also makes the script safe to run under the
 * `valet-gh` name.
 *
 * Caller auth always wins: a set `GH_TOKEN`/`GITHUB_TOKEN` or a completed
 * `gh auth login` (hosts.yml present) short-circuits straight to the real
 * `gh` — the shim never overrides credentials the user chose.
 *
 * The owner/repo hint comes from the current repo's `origin` remote when
 * there is one; outside a repo the request is sent ownerless and the
 * credential route falls back to org-level resolution (`purpose: "api"`,
 * so a sole App installation still yields a token). The token fetch is
 * strictly best-effort and never blocks the command. No token material is
 * embedded; the sandbox token is read from `$VALET_SANDBOX_TOKEN`.
 */
export function ghWrapperScript(apiUrl: string): string {
  const url = `${apiUrl}${ROUTE_PATH}`;
  return `#!/bin/sh
# gh (Valet shim, also installed as valet-gh) — runs the real 'gh' with a
# Valet-resolved GH_TOKEN when you have not authenticated yourself; your own
# GH_TOKEN/GITHUB_TOKEN or 'gh auth login' always wins. Generated by
# @valet/api (engine/git-credential-helper.ts); installed by sandbox prep.
# No token material is embedded here: the sandbox token is read from
# \$VALET_SANDBOX_TOKEN at call time.
set -u

# The real gh: first executable named 'gh' on PATH outside /usr/local/bin
# (this shim's fixed install dir — skipping it prevents self-exec).
real=
oldifs=\$IFS
IFS=:
for d in \$PATH; do
  case "\$d" in /usr/local/bin|"") continue ;; esac
  if [ -x "\$d/gh" ]; then real="\$d/gh"; break; fi
done
IFS=\$oldifs
if [ -z "\$real" ]; then
  echo "gh is not installed in this sandbox image" >&2
  exit 127
fi

# Caller-provided auth wins: env token or a completed 'gh auth login'.
if [ -n "\${GH_TOKEN:-}" ] || [ -n "\${GITHUB_TOKEN:-}" ]; then exec "\$real" "\$@"; fi
if [ -f "\${GH_CONFIG_DIR:-\$HOME/.config/gh}/hosts.yml" ]; then exec "\$real" "\$@"; fi

token=
if [ -n "\${VALET_SANDBOX_TOKEN:-}" ]; then
  remote=\$(git config --get remote.origin.url 2>/dev/null)
  owner=\$(printf '%s' "\$remote" | sed -n 's#.*[/:]\\([^/]*\\)/[^/]*\$#\\1#p')
  repo=\$(printf '%s' "\$remote" | sed -n 's#.*/\\([^/]*\\)\$#\\1#p')
  repo=\${repo%.git}
  resp=\$(curl --max-time 10 -fsS \\
    -X POST "${url}" \\
    -H "x-valet-sandbox: \$VALET_SANDBOX_TOKEN" \\
    -H "Content-Type: application/json" \\
    -d "{\\"host\\":\\"github.com\\",\\"owner\\":\\"\$owner\\",\\"repo\\":\\"\$repo\\",\\"purpose\\":\\"api\\"}" 2>/dev/null) || resp=
  token=\$(printf '%s' "\$resp" | sed -n 's/.*"password"[[:space:]]*:[[:space:]]*"\\([^"]*\\)".*/\\1/p')
fi

if [ -n "\$token" ]; then
  exec env GH_TOKEN="\$token" "\$real" "\$@"
fi
exec "\$real" "\$@"
`;
}
