/**
 * `valet-secrets` — the credential surface an agent gets inside a sandbox.
 *
 * A generated shell script, installed into `/usr/local/bin` by sandbox prep,
 * exactly as `git-credential-valet` is. No runner and no image change: the
 * sandbox already carries `VALET_SANDBOX_TOKEN`, and the API already accepts
 * it on the `x-valet-sandbox` rung.
 *
 * The shape is the Infisical CLI's, and the point is what it does NOT do. An
 * agent says where a secret goes:
 *
 *   valet-secrets run --env GITHUB_TOKEN=op://Eng/GitHub/token -- gh pr list
 *
 * and the value is placed in the child's environment. It is never printed,
 * never returned, and never enters the transcript. A tool that RETURNS a
 * secret puts it in the model's context and in every log downstream of it;
 * naming a destination does not.
 *
 * No token material is embedded: the script reads the creds mount first, then
 * `$VALET_SANDBOX_TOKEN`, the same order the git helper uses. That token is
 * unset before the child runs — it resolves every reference the broker will
 * answer, so a command given one secret must not inherit the key to the rest.
 *
 * Values arrive base64-encoded. A POSIX shell has no JSON parser, and the
 * byte-level extractor this script used cut every value at its first `"` and
 * never unescaped a backslash or newline, so a quoted password or a private
 * key reached the child corrupted but plausible.
 *
 * The body is a JSON-quoted constant rather than a template literal. Shell is
 * full of `$` and `${`, and a template literal interprets both — that
 * escaping is where the bugs were.
 */
const SCRIPT = "#!/bin/sh\n# valet-secrets \u2014 resolve secret references into a command's environment.\n# Generated by @valet/api (engine/secrets-cli-script.ts); installed by sandbox\n# prep. No secret or token material is embedded in this file.\nset -eu\n\nAPI=\"__VALET_API_URL__\"\n\ntoken() {\n  if [ -r /etc/valet/creds/token ]; then\n    cat /etc/valet/creds/token\n  else\n    printf '%s' \"${VALET_SANDBOX_TOKEN:-}\"\n  fi\n}\n\nusage() {\n  cat >&2 <<'USAGE'\nusage:\n  valet-secrets run --env NAME=op://vault/item/field [--env ...] -- <command> [args...]\n\nQuote a reference that contains a space:\n  valet-secrets run --env TOKEN='op://My Vault/GitHub/token' -- gh pr list\n\nThe secret is placed in the command's environment. It is never printed.\nUSAGE\n  exit 2\n}\n\n[ \"${1:-}\" = \"run\" ] || usage\nshift\n\ncommand -v base64 >/dev/null 2>&1 || {\n  echo \"valet-secrets: base64 is missing from this sandbox. Add coreutils to the sandbox image, then run again.\" >&2\n  exit 1\n}\n\n# Pairs accumulate NEWLINE-delimited, not space-delimited: a reference names a\n# vault and an item, and those routinely contain spaces\n# (\"op://ProDex Labs/JumpCloud/password\"). Splitting on whitespace truncated\n# every such reference at its first space.\npairs=\"\"\nwhile [ $# -gt 0 ]; do\n  case \"$1\" in\n    --) shift; break ;;\n    --env)\n      [ $# -ge 2 ] || usage\n      case \"$2\" in\n        *=*) ;;\n        *) echo \"valet-secrets: --env expects NAME=reference, got: $2\" >&2; exit 2 ;;\n      esac\n      envname=${2%%=*}\n      # An invalid name reaches `export` inside eval, and the shell's own\n      # error for a bad identifier quotes the VALUE next to the name. Reject\n      # it here so no shell ever sees the pair.\n      case \"$envname\" in\n        \"\" | [0-9]* | *[!A-Za-z0-9_]*)\n          echo \"valet-secrets: \\\"$envname\\\" is not a valid variable name. Use letters, digits, and underscore, and do not start with a digit.\" >&2\n          exit 2 ;;\n      esac\n      pairs=\"$pairs$2\n\"\n      shift 2\n      ;;\n    *) usage ;;\n  esac\ndone\n[ $# -gt 0 ] || usage\n[ -n \"$pairs\" ] || usage\n\n# One request for every reference: each costs a round trip upstream.\njson_refs=$(printf '%s' \"$pairs\" | sed '/^$/d' | sed 's/^[^=]*=//' |\n  sed 's/\\\\/\\\\\\\\/g; s/\"/\\\\\"/g; s/^/\"/; s/$/\"/' | paste -sd, -)\n\n# Body and status together: -f would discard the body, and the body carries\n# the corrective action the API composed. A bare `curl -sS` treated 401, 403\n# and 500 as success and reported every one as \"nothing resolved\".\nresponse=$(curl -sS --max-time 15 -X POST \"$API/api/sandbox-secrets/resolve\" \\\n  -H 'content-type: application/json' \\\n  -H \"x-valet-sandbox: $(token)\" \\\n  -w '\n%{http_code}' \\\n  -d \"{\\\"references\\\":[$json_refs]}\") || {\n  echo \"valet-secrets: could not reach the broker at $API. Check that the api is running and reachable from this sandbox, then run again.\" >&2\n  exit 4\n}\nstatus=$(printf '%s' \"$response\" | tail -n1)\nbody=$(printf '%s' \"$response\" | sed '$d')\n\nif [ \"$status\" != \"200\" ]; then\n  detail=$(printf '%s' \"$body\" | sed -n 's/.*\"error\":\"\\([^\"]*\\)\".*/\\1/p')\n  [ -n \"$detail\" ] || detail=\"the broker answered HTTP $status\"\n  echo \"valet-secrets: $detail\" >&2\n  exit 4\nfi\n\n# Build the child's environment. Values go straight into variables and are\n# never echoed. A reference nothing resolved is named and the run stops,\n# rather than handing the command an empty credential and a confusing failure.\nexports=$(printf '%s' \"$pairs\" | sed '/^$/d' | while IFS= read -r pair; do\n  name=${pair%%=*}\n  ref=${pair#*=}\n  b64=$(printf '%s' \"$body\" | awk -v ref=\"$ref\" '\n    BEGIN { key = \"\\\"\" ref \"\\\":\\\"\" }\n    { i = index($0, key)\n      if (i == 0) exit\n      rest = substr($0, i + length(key))\n      j = index(rest, \"\\\"\")\n      print substr(rest, 1, j - 1) }')\n  if [ -z \"$b64\" ]; then\n    echo \"valet-secrets: nothing resolved $ref. Check the vault, item, and field names in 1Password, and that the session's org has a service account token connected.\" >&2\n    exit 3\n  fi\n  # The trailing X guards the newline that command substitution would strip:\n  # a private key ends in one, and losing it corrupts the credential.\n  value=$(printf '%s' \"$b64\" | base64 -d; printf X)\n  value=${value%X}\n  printf \"export %s='%s'\\n\" \"$name\" \"$(printf '%s' \"$value\" | sed \"s/'/'\\\\\\\\''/g\")\"\ndone) || exit $?\n\n# The child gets the secret it asked for, not the key to every other one:\n# VALET_SANDBOX_TOKEN resolves any reference this broker answers.\nunset VALET_SANDBOX_TOKEN\neval \"$exports\"\nexec \"$@\"\n";

/** The script, with the API base URL this deployment answers on. */
export function secretsCliScript(apiUrl: string): string {
  return SCRIPT.replace("__VALET_API_URL__", apiUrl);
}
