/**
 * `valet-secrets` — the credential surface an agent gets inside a sandbox.
 *
 * A generated shell script, installed into `/usr/local/bin` by sandbox prep,
 * exactly as `git-credential-valet` is. No runner, no image change: the
 * sandbox already carries `VALET_SANDBOX_TOKEN` and the API already accepts
 * it on the `x-valet-sandbox` rung.
 *
 * The shape is Infisical's, and the point is what it does NOT do. An agent
 * says where a secret goes:
 *
 *   valet-secrets run --env GITHUB_TOKEN=op://Eng/GitHub/token -- gh pr list
 *
 * and the value is placed in the child's environment. It is never printed,
 * never returned, and never enters the transcript. A tool that returns a
 * secret puts it in the model's context and in every log downstream of it;
 * naming a destination does not.
 *
 * No token material is embedded here: the script reads the creds mount
 * first, then `$VALET_SANDBOX_TOKEN`, the same order the git helper uses.
 */
export function secretsCliScript(apiUrl: string): string {
  return `#!/bin/sh
# valet-secrets — resolve secret references into a command's environment.
# Generated by @valet/api (engine/secrets-cli-script.ts); installed by
# sandbox prep. No secret or token material is embedded in this file.
set -eu

API="${apiUrl}"

token() {
  if [ -r /etc/valet/creds/token ]; then
    cat /etc/valet/creds/token
  else
    printf '%s' "\${VALET_SANDBOX_TOKEN:-}"
  fi
}

usage() {
  cat >&2 <<'USAGE'
usage:
  valet-secrets run --env NAME=op://vault/item/field [--env ...] -- <command> [args...]

The secret is placed in the command's environment. It is never printed.
USAGE
  exit 2
}

[ "\${1:-}" = "run" ] || usage
shift

# Collect --env NAME=reference pairs up to the -- separator.
names=""
refs=""
while [ \$# -gt 0 ]; do
  case "\$1" in
    --) shift; break ;;
    --env)
      [ \$# -ge 2 ] || usage
      pair="\$2"
      case "\$pair" in
        *=*) ;;
        *) echo "--env expects NAME=reference, got: \$pair" >&2; exit 2 ;;
      esac
      names="\$names \${pair%%=*}"
      refs="\$refs \${pair#*=}"
      shift 2
      ;;
    *) usage ;;
  esac
done
[ \$# -gt 0 ] || usage
[ -n "\$names" ] || usage

# One request for every reference: each costs a round trip upstream.
json_refs=\$(printf '%s' "\$refs" | tr ' ' '\\n' | sed '/^$/d' | \\
  sed 's/"/\\\\"/g; s/^/"/; s/$/"/' | paste -sd, -)

response=\$(curl -sS -X POST "\$API/api/sandbox-secrets/resolve" \\
  -H 'content-type: application/json' \\
  -H "x-valet-sandbox: \$(token)" \\
  -d "{\\"references\\":[\$json_refs]}") || {
  echo "valet-secrets: could not reach the broker at \$API" >&2
  exit 1
}

# Build the child's environment. Values are read straight into variables and
# never echoed; a reference nothing resolved is named, and the run stops
# rather than silently handing the command an empty credential.
i=1
for name in \$names; do
  ref=\$(printf '%s' "\$refs" | tr ' ' '\\n' | sed '/^$/d' | sed -n "\${i}p")
  value=\$(printf '%s' "\$response" | \\
    sed -n "s/.*\\"\$(printf '%s' "\$ref" | sed 's/[\\/&]/\\\\&/g')\\":\\"\\([^\\"]*\\)\\".*/\\1/p")
  if [ -z "\$value" ]; then
    echo "valet-secrets: nothing resolved \$ref" >&2
    exit 1
  fi
  export "\$name=\$value"
  i=\$((i + 1))
done

exec "\$@"
`;
}
