"""Refresh wheel hashes for existing pins; never changes dependency versions."""
import json
from pathlib import Path
import re
from urllib.request import urlopen


def supported(filename):
    python, abi, platform = filename.removesuffix('.whl').rsplit('-', 3)[1:]
    if 'py3' in python.split('.') and abi == 'none' and platform == 'any':
        return True
    # Production: Debian Python 3.11 on amd64 and arm64.
    if python == 'cp311' and abi == 'cp311':
        return any(tag.startswith('manylinux') and tag.endswith(('_x86_64', '_aarch64')) for tag in platform.split('.'))
    # Local verification: Python 3.14 on Apple Silicon.
    if python == 'cp314' and abi == 'cp314':
        return any(tag.startswith('macosx_') and tag.endswith(('_arm64', '_universal2')) for tag in platform.split('.'))
    return False


if __name__ == '__main__':
    lock = Path(__file__).with_name('requirements.txt')
    pins = re.findall(r'^([\w-]+)==([^\s]+)', lock.read_text(), re.MULTILINE)
    lines = ['# Generated by update-lock.py for Debian CPython 3.11 and local macOS CPython 3.14.', '# Exact direct and transitive pins. Install with --only-binary=:all: --require-hashes.']
    for name, version in pins:
        with urlopen(f'https://pypi.org/pypi/{name}/{version}/json', timeout=30) as response:
            release = json.load(response)
        hashes = sorted({file['digests']['sha256'] for file in release['urls'] if file['packagetype'] == 'bdist_wheel' and supported(file['filename'])})
        if not hashes:
            raise ValueError(f'No supported wheels for {name}=={version}. Check the version and platform filter.')
        lines.append(f'{name}=={version} \\\n' + ' \\\n'.join('    --hash=sha256:' + digest for digest in hashes))
    lock.write_text('\n'.join(lines) + '\n')
