import { jobKickoffCommand, cancelCommand, pollCommand } from "../src/jobs.js";

console.log("UNCAPPED_KICKOFF<<<'EOF1'");
console.log(jobKickoffCommand("repro-uncapped", "sleep 30"));
console.log("EOF1");
console.log("CAPPED_KICKOFF<<<'EOF2'");
console.log(jobKickoffCommand("repro-capped", "sleep 30", 1024));
console.log("EOF2");
console.log("CANCEL_UNCAPPED<<<'EOF3'");
console.log(cancelCommand("repro-uncapped"));
console.log("EOF3");
console.log("CANCEL_CAPPED<<<'EOF4'");
console.log(cancelCommand("repro-capped"));
console.log("EOF4");
console.log("POLL_UNCAPPED<<<'EOF5'");
console.log(pollCommand("repro-uncapped", 0));
console.log("EOF5");
console.log("POLL_CAPPED<<<'EOF6'");
console.log(pollCommand("repro-capped", 0));
console.log("EOF6");
