{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "valet.fullname" . }}-api
  labels:
    {{- include "valet.labels" . | nindent 4 }}
  {{- if .Values.ingress.tls.enabled }}
  annotations:
    traefik.ingress.kubernetes.io/router.tls: "true"
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      {{- if .Values.ingress.tls.secretName }}
      secretName: {{ .Values.ingress.tls.secretName }}
      {{- end }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "valet.fullname" . }}-api
                port:
                  number: {{ .Values.service.port }}
{{- end }}
