/**
 * Auto-discovery script for the v2 plugin bundled registry
 * (plugin-system-v2 plan Task 4).
 *
 * Scans `packages/plugin-*` directories' `plugin.yaml` for manifests opted into v2
 * (`v2: true`, and not `enabled: false`), verifies each opted-in package
 * exposes a `./plugin` export and a `valet.plugin` marker in its
 * `package.json`, and (re)generates `packages/api/src/plugins/registry.gen.ts`
 * with a static import per included plugin, sorted by package name for
 * deterministic output.
 *
 * Run: pnpm tsx scripts/generate-v2-registry.ts   (from repo root)
 */
import { readFileSync, writeFileSync, readdirSync, existsSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { parse as parseYaml } from "yaml";

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(__dirname, "..");
const packagesDir = resolve(repoRoot, "packages");
const outFile = resolve(repoRoot, "packages/api/src/plugins/registry.gen.ts");

interface PluginYaml {
  name?: string;
  version?: string;
  v2?: boolean;
  enabled?: boolean;
}

interface PackageJson {
  name?: string;
  exports?: Record<string, unknown>;
  valet?: { plugin?: unknown };
}

interface IncludedPlugin {
  pkgName: string;
  importName: string;
}

function main(): void {
  const pluginDirs = readdirSync(packagesDir, { withFileTypes: true })
    .filter((d) => d.isDirectory() && d.name.startsWith("plugin-"))
    .map((d) => d.name)
    .sort();

  const included: IncludedPlugin[] = [];

  for (const dirName of pluginDirs) {
    const dirPath = resolve(packagesDir, dirName);
    const yamlPath = resolve(dirPath, "plugin.yaml");
    if (!existsSync(yamlPath)) continue;

    const manifest = parseYaml(readFileSync(yamlPath, "utf-8")) as PluginYaml;
    if (manifest.v2 !== true) continue;
    if (manifest.enabled === false) continue;

    const pkgJsonPath = resolve(dirPath, "package.json");
    if (!existsSync(pkgJsonPath)) {
      throw new Error(
        `${dirName}: plugin.yaml declares v2: true but has no package.json`,
      );
    }
    const pkgJson = JSON.parse(readFileSync(pkgJsonPath, "utf-8")) as PackageJson;

    if (typeof pkgJson.name !== "string" || pkgJson.name.length === 0) {
      throw new Error(`${dirName}: package.json is missing a "name" field`);
    }
    if (!pkgJson.exports || !("./plugin" in pkgJson.exports)) {
      throw new Error(
        `${dirName} (${pkgJson.name}): package.json "exports" is missing the "./plugin" entry required for v2 plugins`,
      );
    }
    if (typeof pkgJson.valet?.plugin !== "string" || pkgJson.valet.plugin.length === 0) {
      throw new Error(
        `${dirName} (${pkgJson.name}): package.json is missing the "valet.plugin" marker required for v2 plugins`,
      );
    }

    included.push({ pkgName: pkgJson.name, importName: "" });
  }

  included.sort((a, b) => a.pkgName.localeCompare(b.pkgName));
  included.forEach((p, i) => {
    p.importName = `plugin${i}`;
  });

  const importLines = included
    .map((p) => `import ${p.importName} from "${p.pkgName}/plugin";`)
    .join("\n");
  const arrayBody = included.map((p) => p.importName).join(", ");

  const contents = `// AUTO-GENERATED by scripts/generate-v2-registry.ts — do not edit by hand.
// Scans packages/plugin-*/plugin.yaml for \`v2: true\` (skipping \`enabled: false\`).
import type { ValetPlugin } from "@valet/engine";
${importLines.length > 0 ? `${importLines}\n` : ""}
export const bundledPlugins: ValetPlugin[] = [${arrayBody}];
`;

  writeFileSync(outFile, contents);
  console.log(
    `[generate-v2-registry] wrote ${included.length} plugin${included.length === 1 ? "" : "s"} to ${outFile}`,
  );
}

main();
