/**
 * `POST /api/sandbox/git-credential` (GitHub/repo integration plan, Task 8)
 * — the in-sandbox credential-minting surface. The git credential helper and
 * `valet-gh` wrapper generated by `engine/git-credential-helper.ts` call this
 * to turn a repo `owner` into a usable git token.
 *
 * ── Auth ─────────────────────────────────────────────────────────────────
 * Sandbox-token only: mounted OUTSIDE the browser-session auth gate but
 * INSIDE the sandbox-token rung of `middleware/auth.ts`'s ladder. That rung
 * verifies the `x-valet-sandbox` header, sets `c.var.sandbox` (the verified
 * `{sessionId, userId, orgId}` principal), and only lets the request through
 * when the path starts with an allow-listed prefix — `/api/sandbox` was
 * added to `SANDBOX_ALLOWED_PATH_PREFIXES` for this route. A missing or
 * garbage token 401s at the middleware before reaching this handler; there
 * is no other credential path in. (The task brief floated `Authorization:
 * Bearer`, but the middleware only reads `x-valet-sandbox` — the middleware
 * is ground truth, so the generated scripts send `x-valet-sandbox` too.)
 *
 * ── Authorization ────────────────────────────────────────────────────────
 * The session id comes from the verified token, never from the body. A
 * bound owner (first path segment of a `session_repos.full_name`, compared
 * case-insensitively) resolves with ITS binding's auth mode, exactly as
 * before. An owner with NO binding — including sessions with no bindings at
 * all, like orchestrators cloning ad hoc — falls back to org-level `auto`
 * resolution for hosts we recognize (github.com only today) instead of
 * 403ing. That grants the sandbox nothing it could not already reach: the
 * same org-level tiers (App installation → user credential → org PAT) back
 * the session's own `github.*` plugin tools, and the sandbox principal
 * carries the same user + org. Unrecognized hosts still 403.
 *
 * ── Resolution ───────────────────────────────────────────────────────────
 * The binding is matched by full `owner/repo` (case-insensitive) when the
 * request carries a `repo`, falling back to the first owner match otherwise
 * (repo absent or unmatched). Matching on the full name matters when a session
 * binds two repos under the same owner with DIFFERENT `auth` modes — each repo
 * must resolve with ITS OWN binding's credential, not whichever happens to be
 * first. The matched binding selects the repo name and the per-binding
 * `auth` mode. The `RepoHost` for that binding's clone URL resolves the
 * token via `resolveGitToken(purpose: "git")`:
 *   - `{token, username}`      → `{username, password: token}`
 *   - `{anonymous: true}`      → `{anonymous: true}` (helper proceeds tokenless)
 *   - `null` (couldn't resolve):
 *       - `auth === "auto"`    → `{anonymous: true}` (degrade to tokenless)
 *       - `auth` explicit      → 409 (the selected credential is unavailable
 *                                 for this owner — a visible failure rather
 *                                 than a silent downgrade the user didn't ask
 *                                 for). The port already distinguishes these
 *                                 two cases (`null` vs `{anonymous:true}`),
 *                                 so no port extension was needed.
 *
 * The token is emitted ONLY in the JSON response body; it is never logged.
 */
import { Hono } from "hono";
import { eq } from "drizzle-orm";
import type { AppEnv } from "../env.js";
import { deriveSecretKey } from "../lib/secret-crypto.js";
import { sessionRepos } from "../schema/index.js";
import { ownerOf, repoOf } from "../services/session-github-token.js";
import { repoHostForUrl, type RepoHostContext } from "../repos/host.js";
import type {
  PostSandboxGitCredentialRequest,
  PostSandboxGitCredentialResponse,
} from "../wire/types.js";

export const sandboxGitCredentialRouter = new Hono<AppEnv>();

function isNonEmptyString(value: unknown): value is string {
  return typeof value === "string" && value.length > 0;
}

sandboxGitCredentialRouter.post("/git-credential", async (c) => {
  // Guaranteed present: the sandbox rung of the auth ladder only lets this
  // path through with a verified principal set.
  const sandbox = c.var.sandbox;
  if (!sandbox) {
    return c.json({ error: "sandbox principal required" }, 401);
  }

  let body: unknown;
  try {
    body = await c.req.json();
  } catch {
    return c.json({ error: "invalid JSON body" }, 400);
  }
  const host = (body as Record<string, unknown> | null)?.host;
  const rawOwner = (body as Record<string, unknown> | null)?.owner;
  const rawRepo = (body as Record<string, unknown> | null)?.repo;
  const rawPurpose = (body as Record<string, unknown> | null)?.purpose;
  if (!isNonEmptyString(host)) {
    return c.json({ error: "host is required" }, 400);
  }
  // `owner` is optional: the git helper always derives one from the clone
  // path, but the `gh` shim can run outside any repo (`gh api /user`,
  // `gh repo list`) and sends an empty owner — org-level fallback handles it.
  const owner = isNonEmptyString(rawOwner) ? rawOwner : undefined;
  // `repo` is optional — the helper only carries it when git sent a path with
  // a repo segment. When present, it disambiguates two bindings under the same
  // owner (each may carry a DIFFERENT auth); when absent or unmatched we fall
  // back to the first owner match (the pre-repo behavior).
  const wantRepo = isNonEmptyString(rawRepo) ? rawRepo.toLowerCase() : undefined;
  // `purpose` picks the resolution ladder (see `services/github-tokens.ts`):
  // "git" (default; installation-first) for clone/push, "api" (user-first,
  // sole-installation fallback) for the `gh` shim's REST/GraphQL calls.
  const purpose = rawPurpose === "api" ? "api" : "git";

  const { db, engineCredentials, encryptionKey } = c.var.providers;

  const bindings = await db.select().from(sessionRepos).where(eq(sessionRepos.sessionId, sandbox.sessionId));

  const wantOwner = owner?.toLowerCase();
  const binding =
    wantOwner === undefined
      ? undefined
      : ((wantRepo !== undefined
          ? bindings.find(
              (b) =>
                ownerOf(b.fullName).toLowerCase() === wantOwner &&
                repoOf(b.fullName).toLowerCase() === wantRepo,
            )
          : undefined) ?? bindings.find((b) => ownerOf(b.fullName).toLowerCase() === wantOwner));

  const ctx: RepoHostContext = {
    orgId: sandbox.orgId,
    userId: sandbox.userId,
    deps: { db, credentials: engineCredentials, key: deriveSecretKey(encryptionKey) },
  };

  if (!binding) {
    // No binding for this owner (or no owner at all) — org-level fallback.
    // `auto` resolution only: it degrades to anonymous rather than erroring,
    // so a public clone in an unbound sandbox still proceeds tokenless.
    const repoHost = repoHostForUrl(`https://${host}/`);
    if (!repoHost) {
      return c.json({ error: "no credential host for this repo" }, 403);
    }
    const result = await repoHost.resolveGitToken(ctx, {
      owner: owner ?? "",
      repo: wantRepo ?? "",
      purpose,
      auth: "auto",
    });
    if (result === null || "anonymous" in result) {
      const anon: PostSandboxGitCredentialResponse = { anonymous: true };
      return c.json(anon);
    }
    const cred: PostSandboxGitCredentialResponse = { username: result.username, password: result.token };
    return c.json(cred);
  }

  const repoHost = repoHostForUrl(binding.cloneUrl);
  if (!repoHost) {
    return c.json({ error: "no credential host for this repo" }, 403);
  }

  const result = await repoHost.resolveGitToken(ctx, {
    owner: ownerOf(binding.fullName),
    repo: repoOf(binding.fullName),
    purpose,
    auth: binding.auth,
  });

  if (result === null) {
    // The host could not resolve. For an explicit `app`/`user` binding this
    // is a real failure the user should see, not a silent downgrade — 409.
    // For `auto`, degrading to tokenless is the documented behavior.
    if (binding.auth !== "auto") {
      return c.json({ error: `the selected credential is unavailable for ${ownerOf(binding.fullName)}` }, 409);
    }
    const anon: PostSandboxGitCredentialResponse = { anonymous: true };
    return c.json(anon);
  }

  if ("anonymous" in result) {
    const anon: PostSandboxGitCredentialResponse = { anonymous: true };
    return c.json(anon);
  }

  // Token material is returned ONLY here, in the response body — never logged.
  const cred: PostSandboxGitCredentialResponse = { username: result.username, password: result.token };
  return c.json(cred);
});
