// AUTO-GENERATED by scripts/generate-v2-registry.ts — do not edit by hand.
// Scans packages/plugin-*/plugin.yaml for `v2: true` (skipping `enabled: false`).
import type { ValetPlugin } from "@valet/engine";
import plugin0 from "@valet/plugin-browser/plugin";
import plugin1 from "@valet/plugin-cloudflare/plugin";
import plugin2 from "@valet/plugin-deepwiki/plugin";
import plugin3 from "@valet/plugin-github/plugin";
import plugin4 from "@valet/plugin-gmail/plugin";
import plugin5 from "@valet/plugin-google-calendar/plugin";
import plugin6 from "@valet/plugin-google-workspace/plugin";
import plugin7 from "@valet/plugin-linear/plugin";
import plugin8 from "@valet/plugin-notion/plugin";
import plugin9 from "@valet/plugin-openai/plugin";
import plugin10 from "@valet/plugin-personas/plugin";
import plugin11 from "@valet/plugin-sentry/plugin";
import plugin12 from "@valet/plugin-slack/plugin";
import plugin13 from "@valet/plugin-slack-user/plugin";
import plugin14 from "@valet/plugin-stripe/plugin";
import plugin15 from "@valet/plugin-telegram/plugin";
import plugin16 from "@valet/plugin-typefully/plugin";
import plugin17 from "@valet/plugin-workflows/plugin";

export const bundledPlugins: ValetPlugin[] = [plugin0, plugin1, plugin2, plugin3, plugin4, plugin5, plugin6, plugin7, plugin8, plugin9, plugin10, plugin11, plugin12, plugin13, plugin14, plugin15, plugin16, plugin17];

/** Brand slug per plugin, from each manifest's `iconSlug`. The connect UI
 * maps a slug to a brand mark; a plugin with no entry keeps the fallback
 * monogram. */
export const pluginIconSlugs: Record<string, string> = {
  "cloudflare": "cloudflare",
  "deepwiki": "deepwiki",
  "github": "github",
  "gmail": "gmail",
  "google-calendar": "google-calendar",
  "google-workspace": "google-drive",
  "linear": "linear",
  "notion": "notion",
  "openai": "openai",
  "sentry": "sentry",
  "slack": "slack",
  "slack-user": "slack",
  "stripe": "stripe",
  "telegram": "telegram",
  "typefully": "typefully",
};
