// AUTO-GENERATED by scripts/generate-v2-registry.ts — do not edit by hand.
// Scans packages/plugin-*/plugin.yaml for `v2: true` (skipping `enabled: false`).
import type { ValetPlugin } from "@valet/engine";
import plugin0 from "@valet/plugin-github/plugin";

export const bundledPlugins: ValetPlugin[] = [plugin0];
